### ISSUE TITLE
Re-add a way to target specific players by name.

### ISSUE THREAD

**Issue by Meowchestra** [Caraxi/SimpleTweaksPlugin#10]
Would it be possible to implement a way to ``/target`` players by their name if nearby? For example ``/target FirstName`` or ``/target FirstName LastName``. This use to be possible but was removed when world visiting was added. I put in the suggestion in the #plugin_suggestions discord channel but figured it would make more sense to be part of SimpleTweaks since it's more of a simple feature.

Functionality for targeting specific party members with ``<#>`` exists but that requires you to be in a party and isn't too helpful with target follow macros.

**Comment by Caraxi** [comment]
Added with tweak in 4bdadf0

**Comment by Meowchestra** [comment]
Thank you so so much! Do you have a test version available for trying it out or should I just wait until the next official update?

**Comment by Caraxi** [comment]
You can get the latest build from the canary repo
Just add `https://repo.caraxian.com` as a third party repo in dalamud settings

**Comment by EmilyLove26** [comment]
I cannot get this to work. What is the correct usage syntax?

**Comment by Caraxi** [comment]
Enable the tweak, then `/target <Name>`
