### ISSUE TITLE
[Visual Bug]Timer on Party Member's Buff not reset when same buff skill recasted from the same source

### ISSUE THREAD

**Issue by exeedz** [Caraxi/SimpleTweaksPlugin#102]
Steps:
1. Go into an instance with a party (the more member the merrier) as Range class (Peloton is the easiest skill for reproducing)
2. Cast Peloton once, watch the buff showing up with the timer on party list buff
3. Then recast it again while the buff still up, some party member's peloton timer on party list don't reset (timer continues from first buff time).

Expected:
when recast buff from same source, party member list's buff timer get reset

Note:
- only tried it when in dungeon with light party, on certain time, whole party member except self got timer not reset, sometimes only 1 or 2.
- also timer got reset when the same buff casted from other party member
- this is only visual bug, so not effecting the real buff timer on party member

**Comment by Caraxi** [comment]
Unfortunately theres not much I can do about it, the game doesn't update the data if it doesn't expect it to change
