### ISSUE TITLE
Possible to denote AM/PM? 

### ISSUE THREAD

**Issue by kodikun** [Caraxi/SimpleTweaksPlugin#12]
I've been unable to find it, but is there a way to denote AM/PM when using the Custom Time Formats feature? I found that using lowercase h and m for hours and minutes will show the time in 12 hour format, but I have been unable to find a way to append AM/PM at the end.

**Comment by Caraxi** [comment]
Use `tt` to show AM/PM
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
