### ISSUE TITLE
Crash caused by UIAdjustments@TimerOnDutyWaiting

### ISSUE THREAD

**Issue by imynwulf** [Caraxi/SimpleTweaksPlugin#122]
I believe there's an issue inside the mentioned tweak in version 1.6.1.0.
Game crashed on queue pops with the mentioned tweak enabled. 
Tested in a party, as well as solo with eureka queues. 
Once crash started happening, it was reproduceable at every queue pop. 
Crash was resolved by removing all simpletweaks configs. 
Crash came back as soon as I enabled the tweak and restarted the game. 
Crash could be resolved by turning the tweak off, regardless of the tweak's status at launch.

**Comment by Caraxi** [comment]
Unsure what could cause this
Added some additional null checking in f341fca89bbd23e2d7136def508149928d04891e but not sure that'll do anything. 

If you could download the [artifact from here](https://github.com/Caraxi/SimpleTweaksPlugin/suites/4207409436/artifacts/108672832) and replace the install of simple tweaks with it and retry it would be great

Just extract the zip into `%appdata%\XIVLauncher\installedPlugins\SimpleTweaks\1.6.1.0` replacing all the files

**Comment by yuri-moens** [comment]
I had the same issue, updated the plugin with the files you gave and it seems to have done the trick. No more crashes on Duty queue pops.

**Comment by imynwulf** [comment]
That appears to have fixed it! I was able to queue into things without crashing.
