### ISSUE TITLE
[Request] Show rested XP amount and percentage

### ISSUE THREAD

**Issue by alexwh** [Caraxi/SimpleTweaksPlugin#123]
As an extra option to the new show experience percentage tweak, it would be nice to show the amount of rested XP stored out of the max possible, as it's not always possible to see the whole bar when nearing the end of a level.

**Comment by Caraxi** [comment]
Added an option to show rested experience with fdc4985cfddf9cbe246a4230ed36e5cb64afc208
Will be available in next update

Not sure if it is exactly what you were looking for, but it'll show how close you are to the limit of rested experience, which is 3 levels (1.5 levels worth of bonus exp)
