### ISSUE TITLE
Bug: New update that happened around October 31st, 2021 cause significant FPS drops when entering combat.

### ISSUE THREAD

**Issue by AkiraChisaka** [Caraxi/SimpleTweaksPlugin#126]
So today I updated the Simple Tweaks plugin, then I notice my FPS drops significantly when entering combat.

My FPS is usually a pretty stable 143 FPS. After entering combat, it drops to around 60.

Disabling Simple Tweaks fixes this issue.

**Comment by AkiraChisaka** [comment]
Update:
Staying in combat was not the issue that causes frame rate drop. Frame rate drop is caused by playing skill animations.

**Comment by AkiraChisaka** [comment]
Update:
Simple Animations like emotes does not cause framerate drops. Seems to only be caused by combat skills that have glow effects.

**Comment by Aireil** [comment]
I would try to disable your tweaks one by one to see which one causes this.

**Comment by AkiraChisaka** [comment]
Good tip, let me try it out.

**Comment by AkiraChisaka** [comment]
Thanks Aireil! Found the issue!

![image](https://user-images.githubusercontent.com/47231500/139620881-7cb163c8-39fe-46d2-ae48-5f2184b89532.png)

New settings for Large Cooldown Counter does not work well with XIV Combo. Seems like intended behaviour.
