### ISSUE TITLE
[Bug] Large CD Cross Hotbar

### ISSUE THREAD

**Issue by phi-lam** [Caraxi/SimpleTweaksPlugin#130]
With Simple Mode unticked, icons on the Cross Hotbar always use the old timer, regardless of setting. Ticking Simple Mode fixes this (all icons use large cooldowns), however I can no longer tweak the font colors.

The font color adjustment was an amazing quality of life improvement, and being able to use that alongside the Cross Hotbar would be fantastic. 

Thanks for all your work!

![image](https://user-images.githubusercontent.com/28878402/140062228-61c27360-827c-4d26-b19e-81c63bcbebee.png)

**Comment by Caraxi** [comment]
Fixed with 9c6a64be45d64c13406b9feec729c7081bf44939 will be added to the release version on next update
