### ISSUE TITLE
[Bug?] Combo Timer plugin disappeared

### ISSUE THREAD

**Issue by KiraSilversoul** [Caraxi/SimpleTweaksPlugin#131]
Really liked using this since it helped me practice my timings, however out of the blue it just up and disappeared. I've messed with X, Y position, font size, color, everything I can to see if I somehow dragged off screen but near as I can tell it just simply is not displaying.

**Comment by Caraxi** [comment]
unhide your parameter bar

**Comment by KiraSilversoul** [comment]
Nice catch, that was exactly it. Any possible way to unhook from parameter bar? If not I can just simply drag those bars off or hide under something since I use a different ui for health/mana

**Comment by Caraxi** [comment]
Added an option to attach it to a UI element that can't be hidden (afaik) Will be available in the next plugin update
