### ISSUE TITLE
[Request] Extend the range for the X Position Offset for Combo Timer's Alternative UI attachment.

### ISSUE THREAD

**Issue by RandomSuggestions** [Caraxi/SimpleTweaksPlugin#134]
Currently it appears the Alternative UI Attachment X and Y Axis will allow you to position the Combo Timer element within 2000 pixels of the top left corner of the screen. The problem is that with super ultrawide resolutions, that won't reach past 40% of the screen at a 5120x1440 resolution..  

It's a niche resolution so I know it's not a high priority, but would it be possible to either double the accepted range on the X Position Offset value or to anchor the UI element towards the middle of the screen so we can also use -X values to position this element?

**Comment by Caraxi** [comment]
Done with 63743a70d89a0c566965af66350cd6ecc91ede0a
Will be available in the next update
