### ISSUE TITLE
[Bug Report]Question about "Large Cooldown Counter"

### ISSUE THREAD

**Issue by zhouhuichen741** [Caraxi/SimpleTweaksPlugin#135]
When "Large Cooldown Counter" is turned on,red numbers are not displayed outside the skill range, and FPS drops after entering combat.

**Comment by Caraxi** [comment]
Thats not a question, its a statement
but I'll have a look

**Comment by Caraxi** [comment]
Hopefully fixed some performance issues with 49fcfa838e25fe5bc8c0207b64eb35aa9d14c5b5
and Added option to use a different colour when out of range with a6a5b31264634836dfcb5c07c92e1f615e52c73d

Will be available in the next update, once it updates (or if you use the artifact) if you still have issues please reopen the issue
