### ISSUE TITLE
Item Hotkeys tweak having issues with Teamcraft

### ISSUE THREAD

**Issue by CharonM72** [Caraxi/SimpleTweaksPlugin#138]
Hello,

For quite a while (like at least a year?), the Item Hotkeys tweak has had issues with opening pages in the Teamcraft standalone application. Hitting the hotkey worked maybe 5% of the time, and hitting it repeatedly would usually eventually get it to open the page (rather like rolling a die over and over until you get a 20). This only applies to Teamcraft, and only to the standalone app (other hotkeys work as normal, and "browser only" mode works normally for TC).

As matter of fact, since TC updated to 9.0.0, I have not been able to get a page to successfully open at all on the app...

I asked around in the TC discord but they suggested asking here.

**Comment by Caraxi** [comment]
nothing has changed, I'm using the methods they provide, if it's broken it's on their side

**Comment by CharonM72** [comment]
Thanks, it looks like it may be an issue with Electron or something along those lines... the TC devs are looking into it.

**Comment by CharonM72** [comment]
Oh, sorry for the lack of update. The Teamcraft dev fixed this. I believe it was an undocumented change in Electron that was a culprit.
