### ISSUE TITLE
Chat Name Colors based on role

### ISSUE THREAD

**Issue by nijow90** [Caraxi/SimpleTweaksPlugin#139]
Hello,

I was wondering if it's at all possible to extend the Chat Name Color functionality to be based on Roles?
(for example Green/Blue/Red chat name colors for Heal/Tanks/DPS)

Also thank you so much for your time and work, your plugin has been a literal game changer

**Comment by LastExceed** [comment]
[PartyIcons](https://github.com/shdwp/xivPartyIcons) already has this. but it only works for players in your vicinity or party, as the client doesnt know the class of players that are far away
