### ISSUE TITLE
Double XHB (simulatneous press) shows mana cost instead of cooldown

### ISSUE THREAD

**Issue by phi-lam** [Caraxi/SimpleTweaksPlugin#141]
![image](https://user-images.githubusercontent.com/28878402/143102045-4d4f369b-6f75-4443-be50-79e6f42ed3d6.png)

**Comment by Caraxi** [comment]
with or without simple mode?

**Comment by phi-lam** [comment]
Sorry I meant to add the details:

simultaneous R2 L2 ON
simple mode unticked

**Comment by Caraxi** [comment]
This will be a pain. might take a while to get it working correctly

**Comment by phi-lam** [comment]
Not too high priority for me at least, the last fix for the cooldowns on
the XHB were great for my needs. Thanks for your work!

**Comment by Caraxi** [comment]
For now I've made the tweak completely ignore that mode of XHB with 6d44dcc594681b0427bec83828db8a4f5b688759
If I make a breakthrough into understanding how it works I'll update it
