### ISSUE TITLE
Custom FreeCompany Tags

### ISSUE THREAD

**Issue by DiggityMan420** [Caraxi/SimpleTweaksPlugin#142]
Can not get color or glow to work correctly exactly what should i try to make it a different color

**Comment by Caraxi** [comment]
various numbers between 1 and 600 will give colours

![cZceCI3.png](https://user-images.githubusercontent.com/11886749/143308070-bee2aea6-36f9-4ea3-a53a-4cb10892871e.png)

**Comment by DiggityMan420** [comment]
ok exactly how do i write it out <colour:????> cuz ive tried <colour:17> and notrhing

**Comment by DiggityMan420** [comment]
see pic not working [PIC](https://imgshare.io/image/r63Du6)

**Comment by Caraxi** [comment]
well it needs to be before the text you want coloured to start with

**Comment by DiggityMan420** [comment]
thank you works
