### ISSUE TITLE
shows Cost instead of CD

### ISSUE THREAD

**Issue by DiggityMan420** [Caraxi/SimpleTweaksPlugin#151]
in Reaper so far the tweak "Large Cooldown Couter" shows no just the cd's but the cost's large too an then reverys back to small so big then small then  big etc... see pic [#1](https://imgshare.io/image/rp2CwY) and [#2](https://imgshare.io/image/rp2SIn)

**Comment by DiggityMan420** [comment]
also I noticed its missing custom free company tags tweak?

**Comment by slashy** [comment]
> in Reaper so far the tweak "Large Cooldown Couter" shows no just the cd's but the cost's large too an then reverys back to small so big then small then big etc... see pic [#1](https://imgshare.io/image/rp2CwY) and [#2](https://imgshare.io/image/rp2SIn)

This seems to be happening only in Simple Mode. If you turn that off it will be fine.

**Comment by goofy-somebody** [comment]
> > in Reaper so far the tweak "Large Cooldown Couter" shows no just the cd's but the cost's large too an then reverys back to small so big then small then big etc... see pic [#1](https://imgshare.io/image/rp2CwY) and [#2](https://imgshare.io/image/rp2SIn)
> 
> This seems to be happening only in Simple Mode. If you turn that off it will be fine.

problem with turning off Simple Mode is that it's needed if you use XIVCombo

**Comment by goofy-somebody** [comment]
OP image links are not working, so this is my cropped screenshot of what it looks like:
![Screenshot 2021-12-10 082424](https://user-images.githubusercontent.com/41055964/145589142-ec4566f4-8084-44ed-93a7-88284201e2ef.png)

**Comment by Caraxi** [comment]
Fixed with 65010c218cadad6e687206b3ce2d67d6be73a72e
