### ISSUE TITLE
Phlegma issue while using Eukrasia with Large Cooldown Counter enabled

### ISSUE THREAD

**Issue by Xiniox** [Caraxi/SimpleTweaksPlugin#156]
If you use Eukrasia with Large Cooldown Counter enabled, Phlegma will get a cooldown counter of 400 during the 1s recast if you have 2 charges.
![image](https://user-images.githubusercontent.com/33554580/145556550-03d228ec-8725-4659-92b2-8dedd4bf7cc9.png)

**Comment by nyxalteria** [comment]
Also happens with penuma but shoves it at 700 and astrologian's macrocosmos

![image](https://user-images.githubusercontent.com/92659516/145563459-640ae59f-2833-4e96-a91c-60aca13a50b5.png)
![image](https://user-images.githubusercontent.com/92659516/145563494-703676cd-e46b-40a4-b747-750a16dd08ed.png)

**Comment by Caraxi** [comment]
Fixed with 65010c218cadad6e687206b3ce2d67d6be73a72e
