### ISSUE TITLE
Issue where phlegma III cool down changes to small sometimes with large cooldown counter

### ISSUE THREAD

**Issue by nyxalteria** [Caraxi/SimpleTweaksPlugin#157]
![image](https://user-images.githubusercontent.com/92659516/145564404-8931dc0c-5776-4cad-a91b-dcf36a206b2b.png)
 I'm not sure whats triggering it, have not noticed this with the earlier versions of phlegma

**Comment by Caraxi** [comment]
Duplicate of #156
