### ISSUE TITLE
Documentation: what does 'GS' mean in enhanced desynthesis UI?

### ISSUE THREAD

**Issue by Ultima2876** [Caraxi/SimpleTweaksPlugin#16]
What does the 'GS' (star) icon mean in the enhanced desynthesis UI? Maybe worth updating the documentation to explain this!

**Comment by Caraxi** [comment]
It means the item is in a gearset

**Comment by Ultima2876** [comment]
That makes so much sense - I've been wondering for weeks, haha.

**Comment by Caraxi** [comment]
I've made it more obvious as to what it refers to as of a1d48b2

![image](https://user-images.githubusercontent.com/11886749/108362168-589d2100-7243-11eb-991b-e571384ef114.png)
