### ISSUE TITLE
[Request] Colouring one's own name in chat

### ISSUE THREAD

**Issue by Gumshoejump** [Caraxi/SimpleTweaksPlugin#161]
I like being able to set name colours for specific people using the chat name colours feature, it makes the chat easier to parse and read! However, it doesn't affect my own name, even when I specify in the settings what colour it should be. It's not a big deal, and it makes sense for my own name to just take on the normal chat colours. But- it would make me happy to be able to set a specific colour for my own character's name! For aesthetic and customization purposes, y'know? It would also assist in making it clearer to my brain at a glance. Thank you for your hard work, also!

**Comment by Caraxi** [comment]
Unfortunately the way the tweak works doesn't support own name because of the way square does it. You should be able to do it with the Chat Alerts plugin though

**Comment by Gumshoejump** [comment]
Ah! I see, I'll try to use Chat Alerts to colour it, then! Thank you again ^^
