### ISSUE TITLE
[Request] Large cooldown counter on charge abilities

### ISSUE THREAD

**Issue by rikodlc** [Caraxi/SimpleTweaksPlugin#162]
The plugin doesn't currently activate if you have a charge available, and some abilities' default counters are REALLY hard to see (namely monk's perfect balance).  I'd love to have the counter always active as long as a cooldown is rolling.

Thanks!

**Comment by nyxalteria** [comment]
Also happens for pneuma / astrologian's draw

**Comment by Caraxi** [comment]
It was supposed to be doing that but a bug was causing it to not
Fixed as of 65010c218cadad6e687206b3ce2d67d6be73a72e
