### ISSUE TITLE
[Bug] Accurate Venture Times visual glitch

### ISSUE THREAD

**Issue by Kurochi51** [Caraxi/SimpleTweaksPlugin#169]
When you hold left click on a retainer, the timer goes back to normal for a brief second. It happens only if you alternate the retainers on which you hold left click, repeatedly holding left click, moving the cursor away, and then letting go won't cause the glitch on the same retainer.

**Comment by Caraxi** [comment]
Fixed with f47300f783edb5a2a76652dd12e835a1af4be737
