### ISSUE TITLE
[Bug] Large Cooldown Counter shows MP cost for a few specific spells while on GCD

### ISSUE THREAD

**Issue by Polarthief** [Caraxi/SimpleTweaksPlugin#172]
![image](https://user-images.githubusercontent.com/31106277/146022914-8eb09896-52df-4163-824e-9a078a962479.png)
![image](https://user-images.githubusercontent.com/31106277/146023184-0c66ef7f-fcdd-4551-b09f-93ee6b271efe.png)

I can't confirm every class (since I don't have them all at 90), but I can at least confirm it's affecting the following classes:
- AST: Macrocosmos
- SGE: Phlegma, Pneuma
- BLU: Numerous. (the ones I've noticed: Cold Fog, Angel's Snack, Ultravibration, Matra Magic, Rose of Destruction, Angel's Whisper, Triple Trident)

**Comment by nyxalteria** [comment]
this was already fixed

**Comment by nyxalteria** [comment]
this was fixed with the recent update for ast/sge and i assume blu as well
