### ISSUE TITLE
Error caught in Large Cooldown Counter

### ISSUE THREAD

**Issue by msoltyspl** [Caraxi/SimpleTweaksPlugin#174]
Hi,

For some reason the large cooldown counter started malfunctioning in my case:

![image](https://user-images.githubusercontent.com/3541095/146106765-cfa4163b-1b54-42f4-ae99-0b4ab17006ea.png)

It's not working anymore, any attempts to disable it causes the above exception to be generated.

Up to today it was working fine, though I did have some weird ff14 crash today as well while experimenting with another plugin - so maybe some data got corrupted.

**Comment by msoltyspl** [comment]
This was happening with 1.6.5.3 . I deleted the plugin (from xivlauncher) and added it again (now it's reporting 1.6.5.4) - the error is not happening anymore.

**Comment by Caraxi** [comment]
Glad it fixed it then
ty
