### ISSUE TITLE
[Feature Request]  Custom colour for shield on HP bar.

### ISSUE THREAD

**Issue by ASPALATHUS** [Caraxi/SimpleTweaksPlugin#176]
I very much like this plugin except for the colour of the overlay.  I tried to edit the colour by fiddling with the config files but didn't find any provision to do so.  Perhaps some RGB sliders could be added?

**Comment by nyxalteria** [comment]
can just use materia ui for that https://github.com/Sevii77/ffxiv_materialui_accent

**Comment by TeaThym3** [comment]
:o 

i will look into it!
