### ISSUE TITLE
crafting costs showing (large cooldown counter?)

### ISSUE THREAD

**Issue by nyxalteria** [Caraxi/SimpleTweaksPlugin#179]
I know there was a recent report about it for healer skills but it's still showing for crafter skills even with the most recent update. The healer part was fixed.

![image](https://user-images.githubusercontent.com/92659516/146458245-c37edb34-4146-4667-a04e-77b321448855.png)

**Comment by Caraxi** [comment]
it's fixed but the update got reverted, so it's broken until the next update

**Comment by nyxalteria** [comment]
ok ty
