### ISSUE TITLE
More graphics related settings.

### ISSUE THREAD

**Issue by Meowchestra** [Caraxi/SimpleTweaksPlugin#18]
This is probably a silly request but would it be possible to implement more graphic options and/or a way to save & load system configuration by presets? 

This request initially came to mind from the "Fixed Shadow Distance" setting being added. I noticed that if you set the distance to 1, _even if you are already on the lowest of the low settings with everything turned off / disabled_, you can squeeze more performance out of the client (~couple fps depending on area). This is especially useful for me since I have an ensemble group.

For graphic options, I'm not too sure what else exists that could be exposed and have an adjustable value for, but two big tweaks could be;

* Being able to change custom resolution lower than 1024 x 720
* Being able to reduce Character and Object Quantity below minimum with a rendering display or network receiving slider (if even possible?)

For the 2nd option, I have just been using the Visibility plugin to hide all Players & Minions which unfortunately doesn't currently support whitelisting specific names to always display.

* Being able to toggle all rendering off
* Being able to change FOV/Maximum Zoom-Out

These two I don't expect to see happen since it probably enters into the realm of abusable and hacky territory -- plus other utilities for camera adjusting do seem to exist. Just would be nice as an addon so it can be controlled and toggled per client more easily.

---

Similar to graphics, I end up having to adjust my System Configuration settings every time I'm not playing on just my main account with all graphics maxed out. This includes unchecking the limit frame rate options under Display Settings, setting graphics to Standard (Laptop) and then turning off wet surfaces, turning off grass quality, lowering map resolution, hiding all shadows, lowering all shadow resolution/cascading/softening, lowering texture filtering, disabling all movement physics, disabling blur/glare/refraction, and then going into Other Settings to lower Character and Object Quantity to Minimum. All because the default presets in the client _don't_ actually have a preset for lowering everything to minimum.

Being able to save the states of System Configuration and load them with one click or command would be nice. For example toggling between full maximum and full minimum.

**Comment by Caraxi** [comment]
This seems too much for simple tweaks. It might be better to have as its own plugin if it is done
