### ISSUE TITLE
Hide Mouse Cursor After Inactivty causes controller-cursor to appear

### ISSUE THREAD

**Issue by SnoFox** [Caraxi/SimpleTweaksPlugin#181]
The Hide Mouse Cursor After Inactivity causes the controller-cursor to appear.

This alone would be ok behavior, but the tweak also seems to be triggering _while_ I'm moving my mouse in a cutscene to select a dialog option.

Videos here until issue acknowledgement: 
- https://snofox.net/share/Screenshot-ARCTIC-2542.mp4
- https://snofox.net/share/Screenshot-ARCTIC-2545.mp4

SimpleTweaks v1.6.5.3
Hide Cursor config:
* Hide after: 3s
* Don't hide in cutscenes disabled
* Don't hide in combat enabled
* Don't hide in instances enabled

**Comment by Caraxi** [comment]
Fixed with ad3988ecb6ca48ebd7cc0ceae45340c2152023f3
