### ISSUE TITLE
[Bug] Chat Color Names not working

### ISSUE THREAD

**Issue by Toxicom** [Caraxi/SimpleTweaksPlugin#185]
Haven't tested if it's only for myself or for others, but I can't set a color for myself. Random color for others works as it should.
![image](https://user-images.githubusercontent.com/69549795/146679035-afdf3832-da89-49fc-9239-54ca84f5bab2.png)

**Comment by Caraxi** [comment]
as stated many times chat colour only affects clickable names so is unable to change your own name
