### ISSUE TITLE
Adjust Equipment Positions does not move position of error icon

### ISSUE THREAD

**Issue by MistressAshai** [Caraxi/SimpleTweaksPlugin#188]
Simply put, when a glamour plate is applied to a gear piece and it doesn't meet the requirements to be used, the error icon wasn't moved.

For example, this headpiece has dancer AF gear glamoured on, but the current job is machinist, so this happens
![image](https://user-images.githubusercontent.com/8222603/146688866-0d7fe162-26ee-4a06-b0ae-070799c151b5.png)

**Comment by Caraxi** [comment]
Ty. I'll get it fixed for next update

**Comment by Caraxi** [comment]
Fixed with 8637556af5e5c8b38bbf53e304f379a87b6b7ec8
