### ISSUE TITLE
[Feature Request] Display Job quests after finishing the MSQ

### ISSUE THREAD

**Issue by E-Ballard** [Caraxi/SimpleTweaksPlugin#190]
Once you finish the MSQ, the Scenario Guide vanishes, taking job quest guides with it, I'm always lost and need to check the wiki to see where the next quest is.

I can't be the only one that thought this should be in game by default.

**Comment by Caraxi** [comment]
![image](https://user-images.githubusercontent.com/11886749/146763993-50b192a2-fccf-449d-a589-bd38f4a65d5a.png)

**Comment by E-Ballard** [comment]
Oh... nvm then. Thanks.
