### ISSUE TITLE
[Feature Request] Option to Change Colour of "Shield on HP Bar" Option

### ISSUE THREAD

**Issue by RyudoGaming** [Caraxi/SimpleTweaksPlugin#193]
I can do this manually, but having an option there to be able to change the RBG values of it would be amazing so we could match with custom UI colours like Dalamud.

The same sort of thing you have implemented with Target HP.

Thank you!

`shieldGrid->AtkResNode.MultiplyRed = 164;

 shieldGrid->AtkResNode.MultiplyGreen = 73;

 shieldGrid->AtkResNode.MultiplyBlue = 164;`

![image](https://user-images.githubusercontent.com/39316798/147238456-56b301de-fe10-477e-a757-fb9b0800320e.png)

**Comment by RyudoGaming** [comment]
If I knew how to make a form and have the variables saved and then used for red, green,blue, then I would.

but that's beyond my skill level.

**Comment by kaedys** [comment]
If you're open to it, there's another mod that handles this, along with many many other tweaks to the party frames: Party List Layout.  It's currently only available if you've selected the option in the Dalamud settings for test releases for mods, but I've yet to encounter any issues with it.  It's also written by Caraxi.

**Comment by Caraxi** [comment]
Added with ff9998611f7ca38880a210f9fb6a1f548aa7e841

**Comment by RyudoGaming** [comment]
I know its been a whilst but just wanted to say thank you for this!
