### ISSUE TITLE
[Issue] The FPS penalty for running XIV Combo with Large Cooldown Counter still have not been resolved

### ISSUE THREAD

**Issue by AkiraChisaka** [Caraxi/SimpleTweaksPlugin#194]
So in a recent update, the Simple Mode of Large Cooldown Counter have been removed.

This makes sense, because the Simple Mode is running into more and more minor issues with Endwalker, since EW added in a lot of white "gauge cost" to the system.

However, the issue with Large CD Counter not being compatible with XIV Combo still haven't been resolved.

For my setup, combat without Large CD Counter will generally be around 105-110 FPS. However, turning on Large CD Counter will cause in combat FPS to drop to around 85-90 FPS.

This is really annoying for me. I do not know if it is possible to fix this issue. In the meantime I will just turn off Large CD Counter for now.

**Comment by Caraxi** [comment]
the issue is in XIVCombo because it doesn't happen for me with my own version of it

**Comment by AkiraChisaka** [comment]
I see, thank you.

Can you tell me which version of XIV Combo are you using? 

Are you just using the official one made by Attick? Or do you have a fork you use yourself?

**Comment by AkiraChisaka** [comment]
Sorry, it seems like you are right.

I tried running the official version of XIV Combo. There are no longer FPS drops anymore.

Furthermore... ignoring Large Cooldown Counter, simply turning off the version of XIV Combo I'm using jumps my FPS from 110 to 180...

Yeah... I'm gonna need to figure out a way for this.
