### ISSUE TITLE
 [Feature Request] clickable class icon on when duty finder pops

### ISSUE THREAD

**Issue by stijnhau** [Caraxi/SimpleTweaksPlugin#197]
according to the new expirimental feature the windows that pops when you have the wrong class for when quuing for the durtyfinder when it pops should also be clickable.

**Comment by Caraxi** [comment]
Ooh that is a great idea

**Comment by Caraxi** [comment]
(Finally) added with 6d25fc5da224313f83f5fd8883c3b0ef639cfc4c
will be available in the next version of Simple Tweaks
