### ISSUE TITLE
[Question] Why not reference FFXIVClientStructs from AppData?

### ISSUE THREAD

**Issue by oorzkws** [Caraxi/SimpleTweaksPlugin#198]
Why this
https://github.com/Caraxi/SimpleTweaksPlugin/blob/8e731f0a1393cceee66701ae3f440c228edfad57/SimpleTweaksPlugin.csproj#L58
and not this?
`$(APPDATA)\XIVLauncher\addon\hooks\dev\FFXIVClientStructs.dll`

Just pulled the project to do some test edits and I was surprised, considering how the rest gets pulled from AppData.

Edit: Though if had done a recursive clone I probably wouldn't have run into this in the first place 😓

**Comment by Caraxi** [comment]
Because Dalamud's version of FFXIVClientStructs is quite often not the latest, only updating when it needs to
