### ISSUE TITLE
[Re-Feature Request] Command "/setopt" added again

### ISSUE THREAD

**Issue by DiggityMan420** [Caraxi/SimpleTweaksPlugin#199]
Can we get the "/setopt" command again i was using it to set legacy cam unless  there is another way

**Comment by HandyDandyMcBrandyRandy** [comment]
Seconded. 
I initially got the plugin specifically for /setopt and would love to see it return.

**Comment by Khelzor** [comment]
Thirded, was super handy for turning legacy mode on and off

**Comment by Caraxi** [comment]
Re-added with 86524e0dafa2c4ffa419b8706791c6a38c5a2695

**Comment by DiggityMan420** [comment]
Thank You Sent from Mail for Windows From: CaraSent: Tuesday, January 25, 2022 10:10 PMTo: Caraxi/SimpleTweaksPluginCc: Wasted Wanderer; AuthorSubject: Re: [Caraxi/SimpleTweaksPlugin] [Re-Feature Request] Command "/setopt" added again (Issue #199) Closed #199.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
