### ISSUE TITLE
Question: Version here is different than the one downloaded via the launcher

### ISSUE THREAD

**Issue by 86Atlas** [Caraxi/SimpleTweaksPlugin#20]
Hi!

Checking the features of this version and the one from the launcher, i noticed that the launcher version has less features (target HP for example)

Is there a way i can force the launcher to use the version provided here instead?

Best regards

**Comment by Caraxi** [comment]
Use the third party repo `https://repo.caraxian.com` and use the canary version. Its intended for testing though so they may be bugs.

**Comment by 86Atlas** [comment]
Thank you!

**Comment by 86Atlas** [comment]
Works like a charm. Your plugin already made the game 100% better.
If you ever decide to mod the party frame/party bars (colors for example) health/mp/tp/limit bars as well, i would be up for testing.
The standard UI is incredibly lackluster in my opinion.
