### ISSUE TITLE
[Feature Request] Automatic FATE Level Sync

### ISSUE THREAD

**Issue by Sn0wCrack** [Caraxi/SimpleTweaksPlugin#208]
Unsure if this would be possible via the plugin, but in-game there is a `/levelsync` command to sync to the FATE level.

Would be really useful for Fate grinding for Relics or Shared FATEs, potentially could set a zone whitelist / blacklist, or maybe a timeout so you have to be in the FATE zone for X seconds before activating the level sync?

**Comment by Caraxi** [comment]
I'm not going to add anything automatic

**Comment by DiggityMan420** [comment]
[Not much differnt fromm this and its automatic](https://imgshare.io/image/rSETJp)

**Comment by Caraxi** [comment]
That doesn't send anything to the server though

**Comment by DiggityMan420** [comment]
> I'm not going to add anything automatic

you have a few  automatic things its not really fair to say that statemnet ( you even just put outa pull request for an automatic "Smart Strafe" switches AUTOMATICALLY

**Comment by Caraxi** [comment]
Maybe check the name on that one. I didn't make that

**Comment by DiggityMan420** [comment]
but i have to say u are the owner u say what's goes in so all around good job but where is the Set option u said was added its still not up or I'm i missing it somewhere

**Comment by DiggityMan420** [comment]
so no worry's i have a side project anyway (private) i added a few things for QOL i do understand not sending anything to the server automatically i get that its risky itself
