### ISSUE TITLE
[Question] In-game audio alerts disabled when running simple tweaks

### ISSUE THREAD

**Issue by Prohono** [Caraxi/SimpleTweaksPlugin#212]
Not sure if its a known issue but I noticed I am not getting the in game audio alerts for certain ability procs (ie when you hit 5 chakras normally theres a pshheww sound effect to let you know you can now use forbidden chakra, when you hit 50 shroud gauge to let you know you can enshroud), 

As soon as I disable/uninstall simple tweaks off in dalamud settings the alerts are back

If i then reinstall and activate simple tweaks, the alerts will remain as well. It seems until i exit the game and restart the game again, where it will again have no audio cue.

Strange issue, not sure if its a particular setting in simple tweaks that might be causing it?

**Comment by wrathfulmonkey** [comment]
I had the same problems when i deactivated the Job Gauge under UI Tweaks.


![image](https://user-images.githubusercontent.com/74739564/148800768-cf3b4d12-93cb-4a05-82a2-b0f54990e2ca.png)

**Comment by Prohono** [comment]
Ahhh beautiful at least now I know which tweak is causing the problem. Thank you for that and I guess I will just drag the gauges to the corner and leave the option off in simpletweaks
