### ISSUE TITLE
[Issue Report] Combo Timer is not work for Monk Combo

### ISSUE THREAD

**Issue by ksledu** [Caraxi/SimpleTweaksPlugin#215]
Hi, Combo Timer is seems like do not support Monk combo in this moment. It is working fine for another melee dps and tank except monk.  It is posssible to add monk in support list? Thank you in advance.

**Comment by Caraxi** [comment]
If its not working then its not using the combo system, monk probably used something different

**Comment by kaedys** [comment]
Monks have status effects that indicate their forms instead.  They do not use the traditional combo system at all.
