### ISSUE TITLE
About supporting Traditional Chinese

### ISSUE THREAD

**Issue by AnyoneCn** [Caraxi/SimpleTweaksPlugin#219]
Because Dalamud does not support simplified Chinese well, can your plugin support traditional Chinese?
As shown in the figure below, there are many characters in Simplified Chinese that cannot be displayed.But traditional Chinese does not have such a problem。
![312312312](https://user-images.githubusercontent.com/86087425/149631764-732d20bf-1bcb-45f7-9846-e01ff030f557.png)

**Comment by Caraxi** [comment]
unfortunately if the characters are in the font theres not much I can really do about it
