### ISSUE TITLE
[Request] Add option to set player name visibility via command

### ISSUE THREAD

**Issue by katarai** [Caraxi/SimpleTweaksPlugin#22]
Currently, the game allows us to toggle player names _on_ during combat, but not off. It would be extremely helpful if we could have a command to set player name visibility to on/off as needed. Opening the character menu every time is far less than ideal.

The four current categories we can configure are '**Party Members'**, '**Alliance Members**', '**Other PCs**', and '**Friends**'. While I think it's outside the scope of this plugin to support automatically toggling names off in battle, I thought it _might_ be in scope to support setting those with commands in the **Set Option Command** options.

If it's possible to add that, I'd be very grateful! :)

**Comment by Caraxi** [comment]
Will be in the next version of SimpleTweaks :)
`/setopt [odn|pdn|adn|opcdn|fdn] [always,battle,targeted,never]`

Added bonus option of Own Display Name (`odn`)
