### ISSUE TITLE
[Bug][ChrDirCommand] Chat directory links opening wrong folder

### ISSUE THREAD

**Issue by gamescom15** [Caraxi/SimpleTweaksPlugin#220]
Clicking on a link from `/chrdir` opens 
* `C:\Users\User\Documents\` 

instead of 
* `C:\Users\User\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn\FFXIV_CHR...`

[`/chrdir open`](https://github.com/Caraxi/SimpleTweaksPlugin/blob/main/Tweaks/ChrDirCommand.cs#L40) works fine, but the [`OpenFolder`](https://github.com/Caraxi/SimpleTweaksPlugin/blob/main/Tweaks/ChrDirCommand.cs#L34) function doesn't. It would probably be interesting to find out what argument that function gets. 

It could also be related to the space in the "My games" folder name.

**Comment by Caraxi** [comment]
Seems like its an issue with the link going over multiple lines. I'll get it fixed
