### ISSUE TITLE
[Bug Report] Set Option Command "Toggle" not working

### ISSUE THREAD

**Issue by Tenrys** [Caraxi/SimpleTweaksPlugin#230]
I use this tweak and command to have a macro allowing me to change between legacy and standard movement to be able to turn in specific situations, but the toggle method doesn't seem to work.

I fiddled with the code a little bit and it seems like the value returned by [this line](https://github.com/Caraxi/SimpleTweaksPlugin/blob/main/Tweaks/SetOptionCommand.cs#L184) doesn't update after changing the option.

**Comment by Caraxi** [comment]
Fixed with 9bee0a78064e01f61dac3752ad935dfd0c1e2ff5
