### ISSUE TITLE
Command Alias - Spacing bug with arguments

### ISSUE THREAD

**Issue by katherto** [Caraxi/SimpleTweaksPlugin#243]
When using the Command Alias tweak and providing an argument, the plugin does not add a space for the command to take effect in the game.

Steps to Reproduce:
- Create Command Alias "mv" for "mastervolume"
- Use the newly created alias in chat such as "/mv 100"
- Error "The command /mastervolume100 does not exist" is produced

Expectation: Passing the argument "100" with the alias should trigger "/mastervolume 100" and work as it used to.

Note: You can currently get around this issue by adding another space before the argument, as in: "/mv __100" (underscores replaced with spaces) but that seems counter-intuitive to how this tweak worked before the recent update.

**Comment by Dranni21312** [comment]
I can confirm. This started happening recently.

**Comment by Dranni21312** [comment]
Note: I believe this regression might have been introduced here:

https://github.com/Caraxi/SimpleTweaksPlugin/commit/2f9d8a5744e3ae8dc71dde16a744e64ee625ee25

**Comment by drejjmit** [comment]
Still an issue in v1.6.8.2

**Comment by Caraxi** [comment]
Fixed with d36b816a8d1416cb732f6aa570721b41c1522ac6
