### ISSUE TITLE
Run backwards in standard movement type

### ISSUE THREAD

**Issue by Samidaro** [Caraxi/SimpleTweaksPlugin#244]
Any way of having your character run backwards like in legacy movement when using standard? thanks

**Comment by ryankhart** [comment]
I'm not a contributor here (yet), but is there any particular reason why you can't just switch it to legacy movement and enable the Legacy Camera Lock feature of Simple Tweaks?

If you're worried about not facing the right way to use certain abilities, there is a setting in FFXIV to have your character automatically face in the right direction when needed.

If you're worried about having your character being able to look away from an enemy when needed, well, that probably requires a playstyle adjustment to address that or else stick with Standard Type movement. I just press B on my Xbox controller to untarget and flick my left thumbstick down a bit to turn away when needed. There are keybinds for those on keyboard/mouse as well.
