### ISSUE TITLE
[Bug/report of a issue] Cannot install Simpletweaks

### ISSUE THREAD

**Issue by Tamamoyomamo** [Caraxi/SimpleTweaksPlugin#248]
So i had Simple Tweaks installed before but it seems after a XIVlauncher update it some how uninstalled itself and it being the only plugin that did so, and i can no longer install it anymore for some unknown reason i got a message on it saying to restart my game and stuff but when i did it the same results. Still cannot install the plugin that i really enjoyed. so the best next thing is to file a report and see if someone or the author has a solution on solving this issue

**Comment by daemitus** [comment]
delete the configuration files in the pluginConfigs folder.
