### ISSUE TITLE
[Bug Report] Shield on HP Bar not working

### ISSUE THREAD

**Issue by RangePup** [Caraxi/SimpleTweaksPlugin#249]
Not sure when it started, but just noticed today that the shield isn't showing up on the HP bar. Tried switching to SMN, SCH, and SGE to see if different classes would do it but no shield showed up. I tried tweaking the color around to see if maybe that was it but that didn't seem to do anything.

**Comment by Nheat** [comment]
I don't know this is the cause of your issue, but something I've observed that breaks the "Shield on HP Bar" tweak is logging out and back in (as in, without closing the game). If you do that, the tweak will not work until you either toggle the tweak off and back on, or simply restart your game.

**Comment by RangePup** [comment]
I did try toggling it on and off and changing the color around but it didn't seem to fix it. When I booted it up next time though it was working just fine, so I don't know what caused the issue or what fixed it besides restarting the game.

**Comment by EpicEric** [comment]
I'm experiencing the same bug, the cause seems to be exactly what @Nheat reported.
