### ISSUE TITLE
Lock/unlock hotbars?

### ISSUE THREAD

**Issue by gucciBane** [Caraxi/SimpleTweaksPlugin#25]
Is there any way to add the lock/unlock hotbars functionality?

**Comment by Caraxi** [comment]
As a command? or automatic based on events?

**Comment by gucciBane** [comment]
I'd take anyhing I could get, to be honest. Being able to do a set command
for it would be ideal so I could put it in macros. Atm I don't have hotbar
1 on my UI, so I can't access it.

**Comment by Caraxi** [comment]
I'll have a look at doing that then

**Comment by gucciBane** [comment]
Awesome, thanks!

**Comment by WesselKuipers** [comment]
I think it would be nice to be able to force lock the hotbars during combat, so that if you click on something you can't accidentally move something around or remove it.
