### ISSUE TITLE
Crafting window: switch jobs when already on the correct job

### ISSUE THREAD

**Issue by daemitus** [Caraxi/SimpleTweaksPlugin#253]
Various recipes, tinctures/potions, some of the snow linen wvr items, likely more are trying to get me to switch to a different job when already on the correct one via synthesize/switch jobs button functionality.

**Comment by Caraxi** [comment]
I'm not experiencing this issue at all, I checked every recipe I could and it all switches to the correct class, or doesn't try switching

**Comment by haojunsui** [comment]
I had a consistent repro on this one. Screenshots provided. I'm on LTW and two items from crafting log shows different synthesize button
Dhalmelskin Leggings of Striking
![image](https://user-images.githubusercontent.com/6809863/156952667-21c48e1d-ac7d-4f37-b08d-cba5025f7fc4.png)
Dhalmelskin Leggings of Scouting
![image](https://user-images.githubusercontent.com/6809863/156952695-1c315290-32fc-4c13-81db-74a34bde259c.png)

I had "hide completed items" setting turned on
