### ISSUE TITLE
stuck in crafting stance unable to exit. even after closing crafting window

### ISSUE THREAD

**Issue by rz-1** [Caraxi/SimpleTweaksPlugin#256]
Hello, found this bug today while crafting.

IIRC steps I did:
1. search for recipe x, y, and z
2. craft recipe x from recipe search
3. switched to recipe y from recipe search
4. I attempted to click switch jobs button and got this error - "Unable to craft. Current class not set to carpenter."
5. I went back to recipe x from recipe search and clicked switch job
6. it started to craft recipe x again
7. exit out of craft
8. switch to recipe y from recipe search
9. switch job to carpenter
10. successfully craft recipe y from recipe search
11. successfully craft recipe z (on carpenter) from recipe search
12. close crafting log
13. stuck in crafting stance

At this point, the /stopcrafting command does not work, and I had to force close the game.

**Comment by Caraxi** [comment]
why not give a specific recipe so I can actually test it in the same exact circumstance

**Comment by rz-1** [comment]
oh, sure. Crafting https://ffxivteamcraft.com/db/en/item/35460/Integral-Earrings-of-Crafting for GC log. So I first search for the recipe by right clicking the log and going into the recipe. Then search for the two intermediate crafts by right click search recipe as well.

recipe x = AR-Caean Velvet 
recipe y = Integral Lumber 
recipe z = Integral-Earrings-of-Crafting

**Comment by JellyBlade** [comment]
I also just encountered this, I was crafting mythril rivets, then went to a previous search entry for linseed oil. I had the improved crafting log tweak enabled when I got stuck. 

Clicking on "end synthesis" on linseed oil after crafting mythril rivets wouldn't trigger my character to switch to ALC/stand up/stop crafting/do anything.

I closed the crafting log, and was unable to re-open it, switch classes, exit crafting manually, or exit/logout without forcing it through task manager.

**Comment by aetepi** [comment]
I've only experienced this when I was force logged out for being AFK and then I logged back in without completely closing the game.  When pressing the button to switch jobs it would cause the hang that required a force close.  I also rarely got a memory exception that would instantly crash the game.
Hoping that can provide some help tracking it down, it's a really useful feature.
