### ISSUE TITLE
[Bug/Feature Missing] Improved Crafting Log

### ISSUE THREAD

**Issue by Shenanagans** [Caraxi/SimpleTweaksPlugin#261]
Started using the Improved Crafting Log a while ago with no issue, however recently (for the last 5 days or so) it vanished from Simple Tweaks config entirely. Is this a bug, or has this feature been removed, and if so, may I request for it to be added back?

**Comment by Caraxi** [comment]
feel free to fix it, but until its fixed it won't be back
