### ISSUE TITLE
[Feature Request] Option to have "Yes" selected by default on popups to enter building/rooms and others

### ISSUE THREAD

**Issue by Aho-Senpai** [Caraxi/SimpleTweaksPlugin#263]
It's mainly for players playing on controller, or ppl who like me use the Numpad0 (default) a lot =)

(Those kind of popups)
![image](https://user-images.githubusercontent.com/52920533/162291260-0c19c80a-174b-47d5-9ea5-328542db17e8.png)

**Comment by alexolivencia** [comment]
I see the option for num0 but it doesn't appear to work for controller. Is that a separate thing? (using "Always Yes" tweak

**Comment by Aireil** [comment]
It should work with the confirm button, whatever that is on controller. I unfortunately don't have a controller to see if it does properly works or not.

**Comment by Aho-Senpai** [comment]
Oh, is that new? nice. 
Also, just tested it on both keyboard and controller for a estate hall door, works fine for both !

Really nice. It's one of those small details that get kinda frustrating over time, so that tweak is a blessing 👍

**Comment by Aireil** [comment]
Yeah, I didn't even see there was an open issue about this, oops. At least it seems to indeed work on controller, nice!

**Comment by alexolivencia** [comment]
> 

I'm unsure if it makes a difference, could definitely be my setup. I'm using Xbox controller with the dongle (that way it registers as Xbox controller to the game) and the game runs in windowed mode. I'll look around to see if there are any conflicts with the other addons. Keybinds are default too.

**Comment by Aho-Senpai** [comment]
Does it just not have it on "Yes" when you open it? what kind of pop-up are you trying it on?

**Comment by alexolivencia** [comment]
Extracting materia from equipment

**Comment by Aireil** [comment]
You didn't uncheck materia extractions in the tweak settings by any chance?

**Comment by alexolivencia** [comment]
![image](https://user-images.githubusercontent.com/28546704/176985681-abe18f9e-26da-4c93-be17-bbb3f97793b6.png)

All checked and nothing in exceptions

**Comment by alexolivencia** [comment]
Oh wait. I think I just misunderstood. It MOVES the cursor to Yes. It doesn't PRESS it for you. Is that it? lol

**Comment by Aho-Senpai** [comment]
Yep. It's a small detail, but so good

**Comment by alexolivencia** [comment]
Ahhh! Okay, I'm sorry for the confusion. In that case, it is working as designed. 

Also, agreed! I think it should be on Yes by default because why wouldn't I want to open the path to continue in this linear dungeon? lol

Thank you for your work. Much appreciated :)

**Comment by Caraxi** [comment]
tweak wouldn't exist if it pressed the button for you
