### ISSUE TITLE
[Bug] Large Cooldown Counter out of range bug.

### ISSUE THREAD

**Issue by ACE1337x** [Caraxi/SimpleTweaksPlugin#27]
Skills that are out of range and on cooldown revert to being small cooldown timers.
![image](https://user-images.githubusercontent.com/11352132/114947570-5d351e80-9e1b-11eb-8ce1-1549bdcc6633.png)

**Comment by Caraxi** [comment]
disable the legacy option or deal with it, there is no way to fix it with legacy

**Comment by ACE1337x** [comment]
the simple option isn't on
![image](https://user-images.githubusercontent.com/11352132/115099750-f93b5480-9f05-11eb-9dfd-f88586deb35a.png)

**Comment by Caraxi** [comment]
Found the issue. Thank you, will be fixed in the next release
