### ISSUE TITLE
[Question] Easy Crafter Switch not there anymore?

### ISSUE THREAD

**Issue by ZyRage** [Caraxi/SimpleTweaksPlugin#270]
Don't know exactly how it was named, but I can't seem to find the option to easily switch crafter jobs without closing the whole crafting window anymore.
Did this got removed?
And if yes will it be added again?

**Comment by Caraxi** [comment]
was removed not long after it was added because it had some major issues causing people to get deadlocked in invalid states. It may return, when I'm motivated enough to work out the issues.

**Comment by ZyRage** [comment]
Thanks for the quick answer (:
