### ISSUE TITLE
[Feature Request] For "Try On Correct Item" provide option to invert default

### ISSUE THREAD

**Issue by ryankhart** [Caraxi/SimpleTweaksPlugin#274]
The "Try On Correct Item" tweak is a very welcome tweak for me, but I would like it to go a step even further and make the original unglamoured look of an item the default for "Try On" and holding shift before doing "Try On" tries on the glamoured version.

I have two reasons why I prefer this:
1. Most of the time, if I'm trying on a glamoured item, it is because I want to check to see if I want to put it in my glamour dresser or not, which immediate strips an item of its glamour. The only time I try on to see what the glamoured item looks like on me is when I'm inspecting other players' glamours. I don't know if it is feasible to detect that situation and provide independent configurations for each separate situation, though.
2. I primarily use a gamepad/controller, so it's far less convenient for me to reach for the keyboard every time I want to try on already glamoured items.

My comments on the last part of reason 1 sparked an even more ideal solution, but it might be less feasible to implement.

If the current window is an examine window for another player, I'd like an option for it to stay the way the game allows me to "try on" as the default. If the current window is anything else (inventory, armory, character, etc.) then I'd like it to default to trying on the unglamoured look. However, I don't think that this should be the default configuration of the "Try On Correct Item" tweak because that would be confusing if the user didn't specifically set it up like that.

I'm also willing to submit pull requests if I figure something out, and I wouldn't need any sort of credit for it in the user UI, not unless I submitted a brand-new tweak to include.

**Comment by Caraxi** [comment]
I've added the simple invert, the conditional invert might happen later but not a priority
