### ISSUE TITLE
Lock window position UI option not appear

### ISSUE THREAD

**Issue by momoeziku** [Caraxi/SimpleTweaksPlugin#275]
Already try and enable the Lock Window Position, but no option to lock when right click on any game windows.
Reload plugin was done too and no different. Kindly assists, thanks!

**Comment by Cloud7050** [comment]
I noticed this after the latest auto-update to V1.6.8.5. It was working perfectly fine before.

Already-locked windows still show up in the dropdown for this specific tweak under the tweaks config, with their unlock buttons. But context menus for locking and unlocking no longer show in-game now.

I tried restarting the client after the auto-update, and toggling the tweak on/off, to no avail.

**Comment by Caraxi** [comment]
The tweak isn't even supposed to be in the current version because context menus are currently disabled by Dalamud.

**Comment by Cloud7050** [comment]
Ah that is a shame to hear, it's probably one of my favourite tweaks. Could you link me to any resources to find out more about this disabling?

**Comment by Caraxi** [comment]
https://github.com/goatcorp/Dalamud/commit/58c63bfedf1f0dec308b146396db0d6e18c75509
this I guess
You can force them enabled with an environment variable, but some people seem to crash a lot

**Comment by Cloud7050** [comment]
Thanks, I shall look into doing so. For this particular tweak, I haven't encountered any crashes.
