### ISSUE TITLE
[bug] Locking windows doesnt work after patch (or dalamud changes?)

### ISSUE THREAD

**Issue by Spazzze** [Caraxi/SimpleTweaksPlugin#278]
hi! 
First of all thanks for the plogon, its awesome and makes a lot of useful tweaks <3 

After 6.1 patch or after some dalamud changes for patch 6.1. feature for locking windows doesnt show up menu 
Windows that was locked before - are locked, I've managed to unlock them only from STP (SimpleTweaksPlugin) Lock config:
![image](https://user-images.githubusercontent.com/8989548/164726315-118138a2-7b50-49ca-a19a-5bf18cb353c4.png)

But menu for lock/unlock doesnt show up anymore. 
![image](https://user-images.githubusercontent.com/8989548/164726532-c4570fc7-6e86-4d2c-a36d-e318c86897c6.png)

Just to be sure, I've made clean re-install of STP (deleting config too), but it doesnt help for menu to show

**Comment by Caraxi** [comment]
context menus are disabled by dalamud currently.
