### ISSUE TITLE
Right click party list to teleport to someone's estate

### ISSUE THREAD

**Issue by FFMaki** [Caraxi/SimpleTweaksPlugin#279]
The right click party list to teleport to estate is no longer an available option. I couldn't find a discord or some link to ask questions so I hope this isn't too bothersome for you guys.

I know that feature has existed before 6.1 cause I used it frequently and searching for it here on your git repository shows that it was implemented at one point. Was it removed for a reason? Will it be back?

**Comment by Caraxi** [comment]
Dalamud context menus are currently disabled so the tweak is too.
