### ISSUE TITLE
Show SlideCast Marker have trouble when use UI mod

### ISSUE THREAD

**Issue by LittleNightmare** [Caraxi/SimpleTweaksPlugin#28]
original in cn:
![image](https://user-images.githubusercontent.com/19811879/115136152-6f4bd280-a050-11eb-8bf7-9f9376ac2228.png)
[discord ui](https://github.com/skotlex/ffxiv-material-ui):
![image](https://user-images.githubusercontent.com/19811879/115136371-f6e61100-a051-11eb-8995-5dd024b81183.png)

IDK how to said it, bug? lol (I spend 30min to figure out what happen)

**Comment by Caraxi** [comment]
Looks like it's working fine, it's just darker than expected because of the UI
