### ISSUE TITLE
[Feature Request] Semi-simplified battle effects

### ISSUE THREAD

**Issue by czlr** [Caraxi/SimpleTweaksPlugin#280]
Currently, the game lets you choose between 3 levels of battle effects: All, Limited, and None.
Limited generally hides everything other than ground effects (nin doton, sch shield, etc.)

For my own character, the only reason I don't use Limited effects is because that also hides AOE animations, which makes it hard to visually confirm how wide I'm hitting

**Ask**
It would be nice to have a semi-limited battle effects mode that only hides single target animations, but still shows ground target effects (same as existing Limited mode) and AOEs

**Comment by Caraxi** [comment]
Use EasyEyes
