### ISSUE TITLE
[Feature Request] For "Try On Correct Item", add optional conditional to invert based on examine window focus

### ISSUE THREAD

**Issue by ryankhart** [Caraxi/SimpleTweaksPlugin#282]
This is part 2 of my other issue #274 that I opened up since part 1 has been implemented and the issue is closed. Thanks so much for doing that!

> If the current window is an examine window for another player, I'd like an option for it to stay the way the game allows me to "try on" as the default. If the current window is anything else (inventory, armory, character, etc.) then I'd like it to default to trying on the unglamoured look. However, I don't think that this should be the default configuration of the "Try On Correct Item" tweak because that would be confusing if the user didn't specifically set it up like that.

I know I'll forget about these wished for features unless I save them in open GitHub issues as ideas for coding projects that I can contribute to that I would care about.

**Comment by Caraxi** [comment]
Will be in the next update
