### ISSUE TITLE
[Feature Request] Legacy Slidecast Style

### ISSUE THREAD

**Issue by ThatsNotAName** [Caraxi/SimpleTweaksPlugin#292]
I know, I know, this is a very pedantic request but I _really_ preferred [the way that slidecast looked in the standalone plugin](https://i.imgur.com/PlQyQIK.png). Could we maybe get a checkbox or something near the slidecast option to return it to this look? Just a simple line wherever the offset it set to? Every caster I've talked to, that has used both, has agreed with me that they miss the old way it looked :( The big box around the end of the castbar just seems really unnecessary. I've seen some people say that something like this was planned but I never found any actual sources on that so I wanted to make an official request.
I don't know anything about coding so if it's too much of a hassle to add in for what it's worth, I understand. Thanks for hearing me out anyways!

**Comment by Caraxi** [comment]
Will be in the next version.
