### ISSUE TITLE
[Feature Request] Auto level sync on FATEs

### ISSUE THREAD

**Issue by RyudoGaming** [Caraxi/SimpleTweaksPlugin#294]
So there is a /command that can be macro'd or keybinded using 

/levelsync 

I am just wondering if it would be a possibility to have the option for it to auto sync you when you enter a FATE,

I've been going back and doing some of the "Shared FATEs" and having to press that sync button is driving me insane, 
sometimes I forget and am I pressing buttons for a few mins before I even realize nothing is happening. 

Many Thanks.

**Comment by Caraxi** [comment]
Not going to happen

**Comment by drejjmit** [comment]
Just macro your main spell? Not that hard
```/macroicon "Heavy Shot"
/levelsync on
/action "Dismount"
/action "Heavy Shot"
```
