### ISSUE TITLE
"Adjust Equipment Positions" tweak doesn't affect UI navigation for gamepad

### ISSUE THREAD

**Issue by ryankhart** [Caraxi/SimpleTweaksPlugin#295]
I like this tweak, but I ended up disabling it because I'm a gamepad/controller user for 95% of the time.

This tweak, UiAdjustments@GearPositions, moves the UI visually, and the new locations work for pointing and clicking with the mouse, but when navigating with gamepad, if I wanted to select the job stone slot, I'd need to navigate to its original position in the bottom right to an invisible slot, which brings the gamepad's focus back up to the new location to the left of the job title and level above the character preview pane.

![Animation](https://user-images.githubusercontent.com/3673962/167044522-246722f4-f0b4-4531-be04-7712e59a1eb4.gif)

**Comment by Caraxi** [comment]
Will be fixed in the next version

**Comment by ryankhart** [comment]
Awesome! I just built from source to test, and it works great! And I love how your code is so readable that it makes a previously daunting task for me into something understandable now. I can see myself using these methods in a plugin of my own for controllers.
