### ISSUE TITLE
[Bug] UiAdjustments@HideJobGauge also hides tutorial prompts

### ISSUE THREAD

**Issue by ryankhart** [Caraxi/SimpleTweaksPlugin#296]
When I was playing as a job where I am currently leveling and receiving tutorial prompts such as these below, when I had the "Hide Job Gauge" tweak enabled, it not only was hidden from me, but as a controller user, I was unable to cycle through HUD elements to interact with other HUD elements until tried uninstalling SimpleTweaks and found it to be an issue with one of the tweaks I had enabled, of which I narrowed down to this one.
![image](https://user-images.githubusercontent.com/3673962/167255467-bea3468b-f156-4311-a622-7beb2512da80.png)

**Comment by Caraxi** [comment]
This is fixed
