### ISSUE TITLE
Right-click context menu missing from Window Lock tweak

### ISSUE THREAD

**Issue by lyonnheartt** [Caraxi/SimpleTweaksPlugin#298]
The option to lock or unlock a window is not showing in the right-click context menu when enabling the Window Lock tweak.

**Comment by Kasper-Who** [comment]
Using v.1.6.9.1 and it looks like this tweak is either removed or disabled. Hoping it comes back.

**Comment by Caraxi** [comment]
It'll be back when Dalamud's context menus return

**Comment by Cloud7050** [comment]
It is possible for users to re-enable context menus via launch arguments / path variables. For the past few weeks, I'd been using things that way. Took me a bit to find out why the context menus stopped showing again. I am also hoping this can return at present (even if more locking can't be done, it was still keeping existing windows locked, and it was still possible to undo locking from the config). Currently looking into disabling auto-updates and using an older version of the plugin

**Comment by Cloud7050** [comment]
For those wondering, from what I could gather, the tweak for locking window positions got put on a blacklist a while back, but the blacklist didn't work. V1.6.9.0 [includes a fix for that](https://github.com/Caraxi/SimpleTweaksPlugin/commit/cceeb00e88bc81e183a29228373eff2c8f7bd529), ie that version update effectively stopped the tweak from "working".

> [Fixed hidden tweaks showing when they were not supposed to](https://github.com/goatcorp/DalamudPlugins/pull/2518)

What I ended up doing was turning off plugin auto-updates in Dalamud settings, and manually reverting to an older version of the plugin (the version just before the blacklist fix, V1.6.8.5). Should you wish to do the same, you can download the raw DLL files and such [here](https://github.com/goatcorp/DalamudPlugins/commit/ec19f7143a15be8704591d48aa07b89edaf566fd), and update your `%appdata%\XIVLauncher\installedPlugins\SimpleTweaksPlugin\` accordingly
