### ISSUE TITLE
Chat tabs squished when in High Resolution UI mode of > 100%

### ISSUE THREAD

**Issue by DarkDestry** [Caraxi/SimpleTweaksPlugin#30]
Screenshots of before and after enabling plugin. Top: Before. Bottom: After.

Note that the chat box tabs are squished together and not properly spaced out.

![image](https://user-images.githubusercontent.com/3728955/115515157-6f99d700-a2b7-11eb-9f59-409270c052e0.png)
<hr>

![image](https://user-images.githubusercontent.com/3728955/115515243-85a79780-a2b7-11eb-80b0-1dd241b10dc0.png)

**Comment by Caraxi** [comment]
Ew. I'll have a look at fixing that :)

**Comment by Caraxi** [comment]
Will be fixed in the next version :)

**Comment by DarkDestry** [comment]
Lovely, Much thanks.
