### ISSUE TITLE
"Disable titlescreen Movie" option causes crash at titlescreen if XIVLauncher is not launched with admin permission since today

### ISSUE THREAD

**Issue by Maaruchann** [Caraxi/SimpleTweaksPlugin#314]
I always started XIVLauncher without admin permission and it worked perfectly but since today i seem to always get this error. The error that is giving me is named: "ffxiv_dx11.exe - exception. Invalid statement An attempt was made to execute an invalid statement." at the titlescreen. This error doesn't occur when i start xivlauncher as administrator. After trying to find out what's the issue i found out checking off the "Disable titlescreen Movie" option in Simple Tweaks plugin fixes this issue and i can start XIVLauncher without admin priviliges again.

**Comment by Caraxi** [comment]
no it doesn't
