### ISSUE TITLE
`/chrdir open` opens Documents instead of char data directory

### ISSUE THREAD

**Issue by shaver** [Caraxi/SimpleTweaksPlugin#317]
`/chrdir` on its own displays the correct path, so it's not a huge deal to copy and paste, but I thought you'd like to know!

**Comment by Caraxi** [comment]
It works fine for me, not sure why you're seeing that issue

**Comment by Rellawing** [comment]
I experienced the same problem. I had to read the character profile that came up in chat and manually click the profile. Rather, it will open chardata, but it won't dive right into the folder it mentions.

**Comment by Caraxi** [comment]
will hopefully be fixed with b575688c1ca4e61f2967fbf4924eab347db3cef1 but I will leave the issue open until Simple Tweaks updates and you are able to confirm

**Comment by Zgred2** [comment]
![image](https://user-images.githubusercontent.com/9273983/184315380-16cda888-bfe5-4bbe-91bb-be0557f5b915.png)

It might be the change to "/" instead of "\" after Documents. "\" is expected for the directory paths in Windows.
