### ISSUE TITLE
Smart Strafe tweak breaks panning in gpose

### ISSUE THREAD

**Issue by gracepetryk** [Caraxi/SimpleTweaksPlugin#323]
**Repro steps**
---
1. enable smart strafe and set out of combat mode to either strafing option
2. open gpose and try to pan the camera left or right

**Expected behavior**
---
Gpose works normally and I am able to pan the camera left or right

**Actual behavior**
---
Pressing the pan keybind has no effect

**Comment by Rueby** [comment]
Having same problem, was driving me abit crazy..
