### ISSUE TITLE
[Feature Request] /autorecom - Automatically equip the recommended gear without a dialogue box popping up.

### ISSUE THREAD

**Issue by Rellawing** [Caraxi/SimpleTweaksPlugin#324]
[Feature Request] /autorecom - Automatically equip the recommended gear without a dialogue box popping up.

This would give us a hotbar button via macros. I don't know about others, but because I haven't found another solution provided by anyone else yet (although I am new to using Dalamud and could be mistaken), I think this feature would add a nice QoL feature to the game by reducing the number of clicks/button presses to get it done.

**Comment by Caraxi** [comment]
I'll have to think about this one, since it would reduce a 3 click operation to a single action

**Comment by Rellawing** [comment]
Thanks for your consideration!

**Comment by Caraxi** [comment]
3357f985fab4613760b093682fc826f8017c93f3 will be in the next update, unless it gets vetoed
