### ISSUE TITLE
[Feature Request] Rank and element in Blue Mage spells' tooltips.

### ISSUE THREAD

**Issue by GudPhrogg** [Caraxi/SimpleTweaksPlugin#328]
Hi,
Could it be possible to add the option to see the rank and element/type of blue mage spells in their tooltips?

I know the element is technically written in the description but some separate text at the top or bottom could make it far less of a pain to check, and rank isn't even referenced at all.

Thanks !

**Comment by Caraxi** [comment]
![image](https://user-images.githubusercontent.com/11886749/173035399-7048d167-27bb-4f9c-8bf7-55311288380d.png)
will be in the next update
