### ISSUE TITLE
[Feature Request] Auto Loop Emote

### ISSUE THREAD

**Issue by eaganlai** [Caraxi/SimpleTweaksPlugin#331]
I don't know if you would be interested to add this to your plugin. So I am just suggesting anyway.

Add a checkbox in the Emotes window, below the "Display Log Message." one. Auto loop any emotes when the checkbox is checked.

I genuinely don't know why it is not an official feature yet, along with all the other things in your plugin.

**Comment by Caraxi** [comment]
Going to reject this for automation, sorry
