### ISSUE TITLE
Plugin fails to load. Re-install attempt prompts to contact dev.

### ISSUE THREAD

**Issue by ZettaLeonhart** [Caraxi/SimpleTweaksPlugin#335]
As mentioned in title. Booted up client, plugins updated, simple tweaks failed. It's listed to be re-installed, however install fails and the error window pops-up saying to restart client or contact dev.

Client restart didn't work.

**Comment by ZettaLeonhart** [comment]
![image](https://user-images.githubusercontent.com/107226414/173465469-49e4a06a-177b-4c97-8520-070f8b727b51.png)

**Comment by altearithe** [comment]
Having the exact same issue.

**Comment by iseohu** [comment]
same thing happened for me. i rebooted the game twice but not working at all

**Comment by Rensa** [comment]
Likewise having the same issue

**Comment by Aireil** [comment]
The issue is with the servers used by Dalamud to download plugins, not related to SimpleTweaks. You can try to install any other plugins, it will fail as well.

Unfortunately, nothing to do other than wait.

**Comment by altearithe** [comment]
Yeah just noticed that another one I had wouldn't either. Definitely Dalamud.
