### ISSUE TITLE
[Feature Request] Seperate Traveler from Wanderer in UiAdjustment/CustomFreeCompanyTags

### ISSUE THREAD

**Issue by Intigracy** [Caraxi/SimpleTweaksPlugin#344]
I would greatly appreciate the ability to change the new Cross-DC FC tag "Traveler" to something separately from "Wanderer" world hoppers.

I understand from looking at the existing code that this would require a rewrite of how wanderer tags are replaced, and I'm willing to pay for the trouble.

**Comment by Caraxi** [comment]
I can do that
