### ISSUE TITLE
[Request] Food and Potion Stats for Crafting/Gathering Stats

### ISSUE THREAD

**Issue by chrystalclear** [Caraxi/SimpleTweaksPlugin#35]
We currently have this functionality for all combat stats, but they aren't available for the 6 non-combat stats: 
- Craftsmanship
- Control
- CP
- Gathering
- Perception
- GP

It would be super useful for determining at a glance without external tools if we'll hit stat thresholds with given setup.

Thank you for your time, as well as all your hard work!

**Comment by Caraxi** [comment]
I'm not sure why you think they would be excluded, but they certainly aren't
![image](https://user-images.githubusercontent.com/11886749/117947052-fdb12c80-b34e-11eb-8e03-f4a20f1312b8.png)

**Comment by chrystalclear** [comment]
I think there was both a combo of me misunderstanding how the stats would be displayed, as well as some sort of glitch in my local system. After uninstalling, reinstalling, and restarting things seem to be working correctly on all classes now.

Apologies for the false alarm, and thanks for your patience!
