### ISSUE TITLE
[Bug] Extra Information on Tooltips causes infinite expanding tooltips when a consumable is on cooldown 

### ISSUE THREAD

**Issue by Korvacs** [Caraxi/SimpleTweaksPlugin#354]
**Description:**

Due to the way FFXIV updates the items in the inventory to increment the cooldown timer, the tweak repeatedly adds a newline above the extra information on every update until the item is no longer on cooldown.

**How to reproduce:**

Ensure the addon is enabled and "Craftable" is selected. Use a consumable with a low cooldown, which is craftable such as a Potion and keep the item hovered.

**Examples:**

![image](https://user-images.githubusercontent.com/1846094/182460541-6548c60e-69db-49ee-80bb-b08e139dee0e.png)

![image](https://user-images.githubusercontent.com/1846094/182460674-917bbe36-aa6c-410f-b628-201dce6c7ab1.png)

**Comment by Caraxi** [comment]
Will be fixed in next version, ty for report
