### ISSUE TITLE
Increased zoom on character previews

### ISSUE THREAD

**Issue by LickOsu** [Caraxi/SimpleTweaksPlugin#360]
It suddenly requires a lot more scrolling than it used to. Is there a way to revert this change, or make it possible for each user to configure?

**Comment by Cloud7050** [comment]
Noticing this as well, around the time of V1.7.4.0.
> [`Increased zoom on character previews`] Adjusted zoom speed

With the tweak off, the jumps between each scroll wheel tick for me are much larger, consistent with vanilla / the old behaviour of the tweak. Not sure what changed. For reference, I'm on Windows and my native OS scroll speed is set to 4 ("Lines to scroll at a time").
