### ISSUE TITLE
Notification Toast Adjustments 

### ISSUE THREAD

**Issue by Miggii** [Caraxi/SimpleTweaksPlugin#362]
After latest update the Big Yellow texts are showing up, im pretty sure i used simple tweaks toast adjustments for it

![Capture](https://user-images.githubusercontent.com/111252159/184556803-0f7d6b96-8a5c-4989-884b-4a02e1888b55.PNG)
.

**Comment by Caraxi** [comment]
Simple tweaks has never hidden those

**Comment by Miggii** [comment]
thought it was simple tweaks. i did have them hidden before. only started showing up after simple tweaks got updated a few days ago
