### ISSUE TITLE
[Feature Request] A Way to Scale Notification Toast Adjustments?

### ISSUE THREAD

**Issue by sudobbq** [Caraxi/SimpleTweaksPlugin#37]
I'd like there to be a way to scale the toast notifications, instead of using the global UI scaler that comes native with the game.
Is this possible?

Here are the current options
![image](https://user-images.githubusercontent.com/6578375/118112883-d3895a00-b3a2-11eb-817b-21a79f99fce5.png)

**Comment by Caraxi** [comment]
Added in next version, when it releases :3

**Comment by sudobbq** [comment]
So fast!  Thank you very much!  And it works! <3
