### ISSUE TITLE
[Feature Request] UiAdjustments@HideJobGauge should hide the job gauge in Island Sanctuary

### ISSUE THREAD

**Issue by MistressAshai** [Caraxi/SimpleTweaksPlugin#378]
Right now, the job gauge will display in the Island Sanctuary with the Show in Duty setting ticked.
It might be worthwhile to add another checkbox for Island Sanctuary in particular or just outright exclude it from the setting entirely because while it is considered a duty, it's essentially its own zone and won't need the job gauge to be there.

**Comment by Caraxi** [comment]
Added with b23c6f60ee773d31975d3eaca1403575e8c7e657
