### ISSUE TITLE
[Suggestion] Add "Auto", "Auto All", and "pass all" buttons to the loot window.

### ISSUE THREAD

**Issue by Adondriel** [Caraxi/SimpleTweaksPlugin#385]
Make it easier to mass roll on loot by adding new buttons.
Auto would need, if item is able to be needed, greed if greedable, and pass otherwise.

**Comment by Caraxi** [comment]
No

**Comment by Adondriel** [comment]
> No

Can you clarify if you are saying no because you don't want to add it or are you saying no because it's not possible?

I understand either way.

**Comment by Caraxi** [comment]
because I'm not making a bot
