### ISSUE TITLE
[Suggestion] Chat command for switching Movement Settings

### ISSUE THREAD

**Issue by JShenobi** [Caraxi/SimpleTweaksPlugin#387]
Since the inclusion of the chat commands to change the name display options, it seems like it might be possible to make a command that does similar for setting movement type (Standard vs Legacy). 

Smart Strafe nearly achieves this but doesn't seem to work all the time and it's not only in-combat / out-of-combat that I'd like to swap.

**Comment by Caraxi** [comment]
did... did you look?
![image](https://user-images.githubusercontent.com/11886749/191648347-d261070f-6ce1-4c96-b449-46aef13b24aa.png)
Its in the same tweak that does display name options

**Comment by JShenobi** [comment]
You know, I didn't. When that tweak debuted I was so stoked about the name display options that I forgot / excluded everything else in the tweak and just thought of it as the "name display tweak." 

My bad, but thank you for the awesome options!
