### ISSUE TITLE
Emote Log Subcommand not working

### ISSUE THREAD

**Issue by lotusflwr** [Caraxi/SimpleTweaksPlugin#404]
I keep my emote log off by default, so I was excited to see this tweak being added for those times I want to make sure someone sees me /wave or something. However, after enabling it I am not seeing the tweak doing anything.

Am I correct in thinking adding "log" is supposed to make an emote slash command print to the log even when "Display log message" is unchecked in the Emote window? Like /wave log or /playdead log acts as though you go in, check Display log message, emote, then uncheck log message again?

If so, the command isn't working for me. I tried toggling it a few times, testing it on a number of slash emote commands, checking for plugin updates, and restarting my client.

Thank you!

**Comment by Caraxi** [comment]
You're correct in how you think it should work, I'll have a look at it to see if I can find out why its not working

**Comment by Caraxi** [comment]
It seems to be working fine for me
![2022-11-22 17 07 22  FINAL_FANTASY_XIV](https://user-images.githubusercontent.com/11886749/203242484-8f4e1fc5-1115-469d-81cd-d89c46be92c1.gif)

**Comment by MidoriKami** [comment]
Their wording was slightly ambiguous.

I believe they were asking for `/wave log` to show a log message with `Display log message.` still disabled
![ffxiv_dx11_YPOgwqE1pK](https://user-images.githubusercontent.com/9083275/203243640-b7831c14-251d-444d-8ce5-e4b3d3f90298.gif)

"I keep my emote log off by default, so I was excited to see this tweak being added for those times I want to make sure someone sees me /wave or something. However, after enabling it I am not seeing the tweak doing anything."

"after enabling it" , I believe they are referring to enabling the tweak, not the log message

**Comment by Caraxi** [comment]
That is exactly what I thought they said
and its working for me

**Comment by MidoriKami** [comment]
Ah maybe this might help, when I `/wave log` with Display log message off I get this
![image](https://user-images.githubusercontent.com/9083275/203244411-8b2aadf1-1be2-4c31-b230-653db0a4d0c3.png)

**Comment by Caraxi** [comment]
How is it possible for struct to be different 🤔 
Hmmm, I'll investigate some more

**Comment by lotusflwr** [comment]
Ok, so it is supposed to work exactly as I thought! I am not very familiar with Dalamud debugging so I haven't been able to find it throwing any errors that I can provide. It just doesn't do anything. :(

I've tried disabling all my other plugins just in case, but still nothing. Emotes work as usual with /emotelog on, but when I do /emotelog off and then use /wave log, for example, I still don't see anything print.

I appreciate the work you're putting into this, and all of of SimpleTweaks, btw! If there's any info I can provide to be more helpful, please let me know. <3

**Comment by Caraxi** [comment]
Reworked the tweak to hopefully make it work better with 1.7.9.1

**Comment by lotusflwr** [comment]
Just updated my plugin and confirm that it's working great now! Thank you so much!!
