### ISSUE TITLE
[Feature Request] Hide Action-Tooltip in Combat

### ISSUE THREAD

**Issue by TheAyes** [Caraxi/SimpleTweaksPlugin#406]
I would like to be able to hide the tooltip that is being shown when hovering over commands or items during combat.

**Comment by Caraxi** [comment]
I can do that

**Comment by Caraxi** [comment]
a58f3696e585efabae466f1caed6412d12842755 Will be in a future version of Simple Tweaks
As it relies on an update to `FFXIVClientStructs` it might not be the next version, but soon enough
