### ISSUE TITLE
Non-coloured desynthesis delta appears twice, overflows window

### ISSUE THREAD

**Issue by dipnlik** [Caraxi/SimpleTweaksPlugin#407]
Enable "Show Desynthesis Skill" tooltip tweak and enable the "Desynthesis Delta" option and disable the "Colour Value" option.
When you open your inventory, hover an empty slot then hover a desynthesizeable item, the delta is shown twice, and can cross the window boundaries.

![image](https://user-images.githubusercontent.com/223484/208235709-473981f1-aa64-47aa-b5fd-20d492064bb2.png)

**Comment by Caraxi** [comment]
I believe this was fixed in #403
