### ISSUE TITLE
Add character limit settings to `/setopt`

### ISSUE THREAD

**Issue by jmerdich** [Caraxi/SimpleTweaksPlugin#421]
FF14 has a number of built-in macros to tweak the effect settings for when you're in large groups. Sometimes, though, the sheer number of players performing actions can impact performance even with everything else down (eg. on hunt trains).

Can the 'character/object quantity' setting be added to `/setopt`? It'd make sense to have it available for use with eg. an "Effects On/Off" macro.

**Comment by Caraxi** [comment]
I can probably do that, the set option command tweak is pending a rewrite though so might be a while

**Comment by Caraxi** [comment]
Took a while, but it is done 9add2c46e0108d1e22f1eb4ce4495c44d2c83b93
will be in the next version
