### ISSUE TITLE
[QoL] Partial matching for /estatelist

### ISSUE THREAD

**Issue by Lynesth** [Caraxi/SimpleTweaksPlugin#423]
Could we get a StartsWith here instead so that I can just `/estatelist bob` instead of having to do `/estatelist bobington superplayer` ?
(I'm using aliases for the people I use that on often meanwhile, but this would be a nice change.

https://github.com/Caraxi/SimpleTweaksPlugin/blob/0fe9e3fa4d73b7ff8a3c8e4593ec06cb80a0d988/Tweaks/EstateListCommand.cs#L49

**Comment by Caraxi** [comment]
Added with a363ee9d648d0e30473e67d0c955f491ff0aabb1
