### ISSUE TITLE
[Request] Emote text additional functionality request

### ISSUE THREAD

**Issue by jamuwu** [Caraxi/SimpleTweaksPlugin#431]
So currently, I understand that the tweak allows showing the log of an emote while the emote log is disabled, and that works great, saves the effort of constantly toggling the emote log. However, I would like to request that additional functionality or another option be added to instead allow me to add more text after the sub command and produce the same effect of using motion and the em commands:
```
/throw motion
/em throws a harmless rock at <t>
```

**Comment by Caraxi** [comment]
Not sure about this since it would technically be 2 commands in one
probably not going to happen

**Comment by jamuwu** [comment]
Oops
