### ISSUE TITLE
[Bug] Graphical Glitch with "Adjust Equipment Positions"

### ISSUE THREAD

**Issue by KevinPugsley** [Caraxi/SimpleTweaksPlugin#433]
![image](https://user-images.githubusercontent.com/12887237/214192454-17b05bf6-dde1-47bc-8ac9-db2827facbc3.png)
![image](https://user-images.githubusercontent.com/12887237/214191715-d496b337-1463-4693-864b-d62fb3f1ac37.png)
Equipment display HUD element is glitched with the "Adjust Equipment Positions" activated. The character sheet itself appears to have no issues and be modified correctly, its only the HUD element.

**Comment by cc12138030** [comment]
Change your UI Resolution Settings to High and this issue should go away.
System Config -> Graphics -> UI Resolution Settings -> Set to "High (WQHD/4K)

I had this same issue when I was using a different computer and changing that setting resolved it right away.

**Comment by Caraxi** [comment]
Fixed in db6e6f6dad1d6d682af9554b9104899f320093d4
