### ISSUE TITLE
Specify pose number for `/cpose`

### ISSUE THREAD

**Issue by PrincessRTFM** [Caraxi/SimpleTweaksPlugin#434]
It would be really nice if it were possible to specify something like `/cpose 2` to go directly to pose 2, rather than having to cycle through `/cpose` until you get the one you want.

**Comment by Caraxi** [comment]
As nice as it would be I don't think its doable without being super detectable

**Comment by PrincessRTFM** [comment]
I'm guessing you don't mean socially, since I doubt anyone would memorise the sequence of poses for each race and go "hey wait, they just skipped like three poses, they must be hacking!" or something.

Oh well, if it's not safe then that's too bad.
