### ISSUE TITLE
[QoL] Left-aligned Target HP

### ISSUE THREAD

**Issue by beeProta** [Caraxi/SimpleTweaksPlugin#436]
In its current state, the UI Tweak for Target HP is right-aligned, which is useful for default, but if you want to say, offset the number to display under the target name instead, you practically have to re-calibrate it every time there's a higher or lower number for its HP. Without over-explaining too much, it's exactly annoying enough to compel me to make an Issue.
That said, an option to change its alignment would be greatly appreciated. ^^

**Comment by Caraxi** [comment]
Added with 0a9f9d808bc49b18c0cdc2656e0c06cba14c12be

**Comment by beeProta** [comment]
Thank you very much!
