### ISSUE TITLE
[Bug] Parameter Bar Adjustments no longer offsets HP bar

### ISSUE THREAD

**Issue by Cloud7050** [Caraxi/SimpleTweaksPlugin#442]
Starting around yesterday, the Parameter Bar Adjustments tweak no longer applies an offset to the HP bar specifically, regardless of what X and Y values are set in the settings. The rest of the features in the tweak still work, such as hiding the HP bar, moving the HP text, and moving the mana bar.

The offsets that aren't applied:

![image](https://user-images.githubusercontent.com/44526554/215319817-adb40a33-77ad-4860-9070-a1c7b4ff155c.png)

Before the bug:

![image](https://user-images.githubusercontent.com/44526554/215319865-b558428f-bd11-486b-a060-726d65f1b79c.png)

Now:

![image](https://user-images.githubusercontent.com/44526554/215319840-864d80f3-e6b1-4202-9872-de865ba889e7.png)

**Comment by Caraxi** [comment]
It is fixed and pending update review by the dalamud team
dc748bec9cb0e0d8b4bd8f5ef8c405e3782db5ec
