### ISSUE TITLE
Leaving crafting window doesn't stop crafting and /stopcrafting doesn't work

### ISSUE THREAD

**Issue by Facecreep** [Caraxi/SimpleTweaksPlugin#456]
The issue occurs while improved crafting log is enabled. When I leave crafting window the character doesn't stop crafting. /stopcrafting just gives me "You can't use that command right now".
In order to stop crafting I have to start crafting something and press "quit" button
While in crafting state I can't open crafting log. I get "That command is unavailable right now" message

**Comment by Facecreep** [comment]
In order to stop crafting I have to start crafting something and press "quit" button

**Comment by Caraxi** [comment]
Share log please

**Comment by Facecreep** [comment]
I'm new to plugins so i have no idea how to share logs. Can I use this guide? https://articles.fflogs.com/help/getting-started

**Comment by Caraxi** [comment]
![image](https://user-images.githubusercontent.com/11886749/218104892-1b0b8f19-8e3f-420b-8791-4ac37346d2ad.png)

**Comment by Facecreep** [comment]
[dalamud.log](https://github.com/Caraxi/SimpleTweaksPlugin/files/10707840/dalamud.log)
Thanks. There it is

**Comment by Caraxi** [comment]
ty
will hopefully be fixed with https://github.com/Caraxi/SimpleTweaksPlugin/commit/6551ae77bbd24384c57bd28b4ec6843a71b071dd
