### ISSUE TITLE
[Feature Request] Loot Need All, Greed All, Pass All - and Automatic Settings

### ISSUE THREAD

**Issue by Rellawing** [Caraxi/SimpleTweaksPlugin#458]
[Feature Request] Loot Need All, Greed All, Pass All - and Automatic Settings

1. I propose that there should be a tweak that: Handles setting auto looting based on conditions:
- Set a level threshold (Say Level 80) (or ilevel instead?) that allows us to automatically pass on anything less than the specified). This would probably be housed in the tweaks as some are.
- Based on types of instances, Dungeons, Trials, Alliance Raids, Normal Raids etc...

2. Additionally, new buttons added to the loot box for Need All, Greed All, Pass All

These would be a huge QoL boost. I hope others agree.

**Comment by Caraxi** [comment]
> Automatic 

no
