### ISSUE TITLE
[Request] Filter Classes/Jobs on Item Tooltips

### ISSUE THREAD

**Issue by eldornoftw** [Caraxi/SimpleTweaksPlugin#463]
Hi there, I've had this idea for a simple plugin for a while, and someone mentioned that it sounded perfect for a Simple Tweak.

You know how on item tooltips it shows which classes/jobs can equip the item, like "PGL LNC MNK DRG SAM RPR" - it would be really useful if you could filter this list to only show the _jobs_ and not the base classes (i.e. just show "MNK DRG SAM RPR"). 
Potentially, you could show the base classes instead of their corresponding jobs before you've unlocked them (so at low levels you'd see "PGL LNC SAM RPR"). I think this would make it a lot easier to read at a glance.

If this would be possible, I'd be really grateful 🙂

Thanks,
-eldo

**Comment by Caraxi** [comment]
https://github.com/Caraxi/SimpleTweaksPlugin/commit/e0d36d8ede64157c2b01787d6431b183c5be1809
Done

All jobs unlocked:
![image](https://user-images.githubusercontent.com/11886749/218735764-0152910d-897c-4d4b-8400-d34cadd65a74.png)

Summoner not Unlocked:
![image](https://user-images.githubusercontent.com/11886749/218735881-28a08a23-e4ac-4e1e-b558-7439aa268d1d.png)

**Comment by eldornoftw** [comment]
Incredible, thank you so much!
