### ISSUE TITLE
Combat Movement Type Control 

### ISSUE THREAD

**Issue by xMrShadowz** [Caraxi/SimpleTweaksPlugin#467]
This tweak does not work on controller.

**Comment by xMrShadowz** [comment]
I was able to find a workaround for anyone else who needs this. 
General tweaks> Set Option Command (check this)
create a macro /setopt LegacyMovement toggle or /setopt lm toggle
to save hotbar space you can make this macro on slot 98 or 99 then go to system config>gamepad settings>button configuration and assign "Execute Macro #98(99) to whatever is comfortable for you.

**Comment by Caraxi** [comment]
Should be fixed in next version, please reopen and let me know if it is not
