### ISSUE TITLE
Stop flag placeholder from being automatically appended to chatbox input

### ISSUE THREAD

**Issue by PrincessRTFM** [Caraxi/SimpleTweaksPlugin#47]
Nine times out of ten, when I use a map flag it's purely for myself so I can easily tell where the location I want to go to is relative to me. It makes it easier to tell when I've arrived by looking at the minimap, as well as knowing exactly which direction I need to go at any given time. The way that the game automatically appends `<flag>` to the chat input box when I set the flag is just annoying, because I always need to clear it when I'm trying to chat with people while traveling. If possible, I would love it if there was an option to stop the game from doing that.

It seems to not append it if it's already present, so maybe the check could be overridden to always return true, if that would be easier than blocking out the part responsible for inserting it.

**Comment by Caraxi** [comment]
Almost a year later, will be in the next update.
