### ISSUE TITLE
Job Switcher doesn't seem to work for DoH Jobs.

### ISSUE THREAD

**Issue by goodiesohhi** [Caraxi/SimpleTweaksPlugin#472]
The Character Window Job Switcher doesn't work for Disciple of the Hand jobs, it doesn't even show the message for you not having a gearset for jobs with no gearsets. Nothing happens.

**Comment by Caraxi** [comment]
works fine for me
please show dalamud.log

**Comment by goodiesohhi** [comment]
[dalamud.log](https://github.com/Caraxi/SimpleTweaksPlugin/files/10833787/dalamud.log)
This is just me clicking on every class, none of the DoH one's do anything for me. Only the other classes even report that they were clicked.

**Comment by gnbezerra** [comment]
@Caraxi, I can improve on this report.

Currently, DoH class switcher only works if desynthesis is unlocked for that class (i.e. lvl 30+).

How to reproduce this bug:
- Turn job switcher on;
- Have a character with a DoH class unlocked and level less than 30;
- Try to click the class icon.

**Comment by Caraxi** [comment]
Fixed with 8d3d9dc9d347c196d3993ce274539bffb0658f11
