### ISSUE TITLE
Simplified Equipment Job Display doesn't work on Japanese client

### ISSUE THREAD

**Issue by redchar** [Caraxi/SimpleTweaksPlugin#498]
Simplified Equipment Job Display tweak doesn't seem to be doing anything at all on Japanese language.

For example, ninja items still show 双剣士 忍者 instead of just 忍者

**Comment by Caraxi** [comment]
Oh... does japanese client show full job names instead of abbreviations

**Comment by redchar** [comment]
Yes, Japanese client uses full names of the jobs, not NIN etc.
For example:
![ffxiv_dx11_2023-03-09_183929](https://user-images.githubusercontent.com/9455120/224185483-f71602dc-5de1-405e-b90b-a88519142cf6.png)
first one is ROG, second is NIN

Full list is available here:
https://jp.finalfantasyxiv.com/lodestone/playguide/db/text_command/19a6c51f41d/

**Comment by Caraxi** [comment]
I'll see if I can fix it

**Comment by Caraxi** [comment]
c4776cc73a509d708e2c61af2ad59c2c6d3902fc
Will be fixed in the next update
