### ISSUE TITLE
Desynth window:  level < +50 color differently.

### ISSUE THREAD

**Issue by daemitus** [Caraxi/SimpleTweaksPlugin#50]
I typically GC turnin anything that isn't going to give me any skill ups. It would be nice if the +0 -> +50 range was colored slightly differently so as to differentiate from the general "greater than my current desynth level" green coloring.

**Comment by Caraxi** [comment]
![image](https://user-images.githubusercontent.com/11886749/123822175-332fca80-d93b-11eb-8b2d-f45d618d063d.png)
Done

**Comment by daemitus** [comment]
Looks perfect.
