### ISSUE TITLE
Bring back gamepad option for /setopt

### ISSUE THREAD

**Issue by Bonsailinse** [Caraxi/SimpleTweaksPlugin#502]
Hey. [This commit](https://github.com/Caraxi/SimpleTweaksPlugin/commit/3d42fab066a8047c499220e6756a362b1a303183) included a rewrite of the /setopt command and didn't include the gamepade mode attribute, /setopt gp [on/off/toggle].

I don't know if it is an oversight or you have reasons for it but it would be great to have it back.

Thanks a lot for everything you do!

**Comment by eat-a-pitta** [comment]
yes please!! I constantly rely on this setting because I play with controller on certain jobs and kb&m with others. like OP said, this change was not written in the changelog so I'm not sure if it was intended.. would really appreciate getting it back.

**Comment by TheTylerG** [comment]
I was so confused when I logged in and my controller toggle button wasn't working. I switch to controller for gathering.

**Comment by Caraxi** [comment]
Sorry, it was accidentally removed
Will be back in the next update e6077a6a1d25e7ec5f7b8aea6bc9511ac32d4b10
