### ISSUE TITLE
[Bug] Fade Unavailable Actions incorrect fade when changing gearset

### ISSUE THREAD

**Issue by diwo** [Caraxi/SimpleTweaksPlugin#503]
1. Enable "Fade Unavailable Actions"
1. Enable "Apply Only to Sync'd Actions" sub-option
2. Changing gearset to another job

Hotbar slots occupied by actions unavailable to the previous job are faded even when the slots have been replaced with actions that are available to the new job.

**Comment by Cloud7050** [comment]
In the time I was testing out and typing up #504, it seems this issue got posted. That other issue details this behaviour among other things. Perhaps worth closing this and discussing it over there?

**Comment by diwo** [comment]
Fixed in 1.8.4.0
