### ISSUE TITLE
[Feature Request] Setoption for 'Limit mouse operation to game window.'

### ISSUE THREAD

**Issue by elshandra** [Caraxi/SimpleTweaksPlugin#506]
Hi Team,

A common problem regarding mousedown/mouseup events facing people running the game under Linux is resolved by enabling the 'Limit mouse operation to game window' option in /sconfig.

If this could be made available to /setoption and bound to a key, this would be of great help to those of use who run the game on linux.

It would be better again, if we could have this automatically enable while in combat.

It would be even better, if this could just be enabled for drag operations.

The issue is, if you are holding the mouse (right or left) down to drag the camera, and drag so the OS thinks the cursor would be on another screen, the client won't register the mouse up event. This means, you end up with your mouse being locked until you click it. The work around is to lock the mouse to the client using the above option, but currently, the only way to do this is by going into /sconfig and ticking or unticking the box.

It would be a hug QoL improvement for linux users, if you make this operation less cumbersome.

**Comment by Caraxi** [comment]
Will be in the next update 092670ad009e66732c3cd3cb56f334f11a03b705
