### ISSUE TITLE
[Bug] Block Targeting Treasure Hunt Enemies blocking Alexandrite Maps

### ISSUE THREAD

**Issue by ArmonyDragon** [Caraxi/SimpleTweaksPlugin#510]
The "Block Targeting Treasure Hunt Enemies" tweak is incorrectly blocking the ability to target mobs spawned from your own Alexandrite Maps.

**Comment by Caraxi** [comment]
36d0d4a8e43882a4894002ad39352a7ffe202ef9
Fixed next update
