### ISSUE TITLE
[Bug - Set Option Command] GameMode (gm) not displaying

### ISSUE THREAD

**Issue by auroraisluna** [Caraxi/SimpleTweaksPlugin#511]
Command `/setopt gp [value]` is no longer available and also does not show in the list:
![image](https://user-images.githubusercontent.com/98479040/224478725-7c813ced-3f2f-45da-9819-76ae27904989.png)

**Comment by Caraxi** [comment]
It is fixed in the pending version update.
Sorry for the inconvenience.
