### ISSUE TITLE
Please change ConditionChange 

### ISSUE THREAD

**Issue by 53m1k0l0n** [Caraxi/SimpleTweaksPlugin#512]
https://github.com/Caraxi/SimpleTweaksPlugin/blob/6ac3d68c2606301c0381c389670b783f2cebd1db/Tweaks/CombatMovementControl.cs#L70

It's a bit annoying everytime with Weapon Unsheated and you finished a fight, it change the Movement.

**Comment by Caraxi** [comment]
then don't use the tweak?

**Comment by 53m1k0l0n** [comment]
Sure i'm dumb
