### ISSUE TITLE
[Bug] Refresh Market Prices Tweak Freezing the Market Board

### ISSUE THREAD

**Issue by spval** [Caraxi/SimpleTweaksPlugin#527]
Starting yesterday, whenever the market board refreshes through the Refresh Market Prices tweak the entire market board interface freezes and I'm unable to interact with it, whether that be to purchase an item or to close the window normally. This occurs in both kb+m mode and gamepad mode. With gamepad I'm unable to toggle through windows to select it. The only way to close the mb once this happens is a hard close through the use of esc or start (gamepad).

**Comment by Caraxi** [comment]
Fixed with 0d4f3f301cb74291b4977cbe132201d21c442c13
Tweak has been disabled until the plugin is updated
