### ISSUE TITLE
[Bug] Simplified Equipment Job Display tweak missing

### ISSUE THREAD

**Issue by eldornoftw** [Caraxi/SimpleTweaksPlugin#533]
Heya Caraxi,

A month or so back you implemented the `Simplified Equipment Job Display` tweak #463 and it was working perfectly for some amount of time (thank you again!); however I recently noticed that the classes are all showing again, and after updating plugins and checking the Simple Tweaks settings, I am now unable to find the option at all. Not sure what happened to it, but I was hoping you could please take a look, hopefully it's a simple fix 😅  

Thanks in advance,
-eldo

**Comment by Caraxi** [comment]
All tooltip based tweaks are currently disabled due to issues crashing the game. they will be back when I can work out the issue

**Comment by eldornoftw** [comment]
Ah okay, no worries!
