### ISSUE TITLE
No jokes please

### ISSUE THREAD

**Issue by Waitsnake** [Caraxi/SimpleTweaksPlugin#539]
I had random animations in character view and character login screen (hearts, sleeping bubbles and other animations over character).
I was wondering about an malicious infection/attack of my FFXIV game.
- I restarted game -> haunting animations still there in character login screen
- I restarted computer -> haunting animations still there character login screen
- I disabled dalamud completely -> character login screen finally normal
- I enables dalamud but disabled all plugins -> character login screen still normal
- I enabled plugins on by one -> as soon as SimpleTweaksPlugin was active the animations haunting my character where back in login screen
- I found the option "No Jokes" in options of SimpleTweaksPlugin flashing in all rainbow colors -> after I enabled "No Joke" option character login screen finally normal

=> finally I uninstalled SimpleTweaksPlugin 

This is not funny in my opinion, since it randomly hits the user out of nowhere like a malicious software does.

![no_jokes_simple_tweaks](https://user-images.githubusercontent.com/942085/229246674-b1b4bc53-6369-4e54-b821-be314efcead4.PNG)

**Comment by Caraxi** [comment]
Good riddance

**Comment by jmpnul** [comment]
Personally I think the joke was fine, and funny. Just maybe put a little warning that this is plugin related *before* I outed myself to everyone that I'm a dirty plugin user haha. I thought it was the game devs playing a lil april fools prank.

**Comment by Waitsnake** [comment]
It seems to me, that not in every culture around the globe the April fools pranks are going so wild as in the English speaking world. Where I life it could happen that a friend or a college mentions that your shoelaces are untied or that you have spilled coffee on the shirt and after you look at it he says "April, April!". Thats it mostly. 
When I was pranked by the plugin it was after shortly after the date had switched at midnight and in this tired mindset I had not the slightest idea that this could be a tough April joke. That is why I never mentioned April fools day in my ticket. At night I was still not aware it was only an April fools joke. I was only thinking some malicious gaming hacks starting going wild like they did in other games like GTA Online. And that now SimpleTweaksPlugin is one of them.
I guess if you live in countries that are more used to coarse jokes on this day it was fine and funny. Even I think the heart animation was cute after sleeping a night over it. ^^

**Comment by Caraxi** [comment]
If you think a heart animation is a coarse joke...

**Comment by Waitsnake** [comment]
It is hard as non native speaker of english to have a feeling how strong words appear for a native speaker. Sorry if 'coarse' sounded too strong. In my native language I would have used the word 'deftig'.
