### ISSUE TITLE
[Request] AFD opt-in?

### ISSUE THREAD

**Issue by Mokura** [Caraxi/SimpleTweaksPlugin#540]
Perhaps I'm being a bit humorless, in which case I sincerely apologize.  But having settings change (though completely harmless in this case) quite abruptly, even on (or especially on, depending on your field) April Fool's Day is a bit startling and might lead folk into thinking something is broken, or that other things are broken.  I appreciate the banner notification, at least.  Would it be worth considering, in the future, adding an opt-in notice on Simple Tweak's setting screen to enable the joke during the lead-up to April Fool's Day?  It might mean it's less of a 'prank', per se, but pranks with things installed on end users' computers can be pretty alarming.

**Comment by Caraxi** [comment]
Fuck off
