### ISSUE TITLE
April Fool's Joke doxes other players

### ISSUE THREAD

**Issue by MixMuffins** [Caraxi/SimpleTweaksPlugin#541]
In-game portraits show other users of simple tweaks with the april fool's "Sleep" animation, letting you know who else in your party is using the add-on. This could be considered "doxing" and allow malicious individuals to mass-report others for use of 3rd party add-ons. 

tl;dr: New april fool's joke lets other users of simple tweaks know who ALSO uses the tool without their consent. Big no no.

**Comment by MidoriKami** [comment]
The feature is client-side-only, you can view the code for the feature yourself to confirm this. 
No network data is sent to or from other players.
