### ISSUE TITLE
[Bug] Hide tooltips in combat removes tooltips permanently

### ISSUE THREAD

**Issue by solarscrolls** [Caraxi/SimpleTweaksPlugin#551]
I enabled hiding item tooltips in combat, but out of combat they don't show up anymore either.
Disabling the tweak or fully disabling the addon and restarting the game doesn't bring them back either. I'm stuck without any tooltips and can't find a way to bring them back.

**Comment by Caraxi** [comment]
If they got stuck somehow, enable them using the vanilla game settings

**Comment by Rellawing** [comment]
I encountered this bug too, so I turned it off and stopped having the issue where the tooltips would be turned off. You can turn them back on in the settings, but inevitably, they get turned off again. At first I freaked out, finding them entirely gone. It took a little while to track down where they went.

**Comment by solarscrolls** [comment]
I found the setting, didn't know that it existed. Still kinda annoying how it doesn't toggle them back on, but it's not as detrimental as I initially thought. Still, the tweak feels kind of useless atm due to it just turning them off and not turning them back on, which I might as well do manually for now.

**Comment by Caraxi** [comment]
Disable it then. It works fine most of the time it just seems to get stuck for some people for some reason
