### ISSUE TITLE
[Bug] High Resolution Screenshots tweak breaks resolution if used multiple times in a row

### ISSUE THREAD

**Issue by HoloWise** [Caraxi/SimpleTweaksPlugin#554]
As in title. If user accidentally presses screenshot button twice the function will attempt to increase an already increased resolution and then reverting back to original resolution will fail, resulting in broken (small and misplaced) UI and mouse interacting with UI elements that are increasingly offset from the actual mouse placement as the mouse gets away from 0,0 corner

**Comment by Caraxi** [comment]
Should be resolved with 54cb9a29629c456ec4b3c68f8f1ad216c2d42dc0
Will be in the next update
