### ISSUE TITLE
[Bug?][Hide Tool tips in Combat] Does not revert to original settings when disabled?

### ISSUE THREAD

**Issue by Rueby** [Caraxi/SimpleTweaksPlugin#557]
I'm not sure if this is a dalamud issue or a simple tweaks issue. This is the only tweak that I can think of that messes around with the tool tips for me and the ones that were disabled were the ones I disabled in the plugin (Item Tool tips & Hide popup Help)
Here's my tweak settings
![image](https://user-images.githubusercontent.com/92205577/230813377-a2d8a7fe-8b24-4b60-87c3-f06a00831f74.png)

This is what I found disabled despite not having any plugins/tweaks on.
![image](https://user-images.githubusercontent.com/92205577/230813504-79df5e0f-b8fa-475d-b896-c12f0a0c70d7.png)

Issue : 
Logged in and the tooltips for inventory items  (item and pop up help) were disabled) I spent awhile trying to find out why this was happening.

I disabled the Tweak to see, (tooltips hidden).
I disabled the Simple Tweaks plugin to see, (tooltips hidden).
I disabled all third party plugins, (tooltips hidden).
I ran dalamud without plugins, (tooltips hidden) - Empty installedPlugins folder
I ran the game without dalamud from the launcher, the tooltips were showing.

I tried it in combat and disabled and enabled the tweak a few times and it seems to be working fine for now..Could this be a really unfortunate coincidence? I never even touched that menu and I had to look it up to see where those settings were.

**Comment by Caraxi** [comment]
I've improved the logic to hopefully avoid this happening again in the future.
Should see some improvement with this issue in the next update.

203246efbd818c0f952143885652c13a789e09bb

**Comment by Rueby** [comment]
Thank you so much, Cara!
