### ISSUE TITLE
Track Faded Orchestrion Rolls not working

### ISSUE THREAD

**Issue by Eleida** [Caraxi/SimpleTweaksPlugin#561]
What it says on the tin.

The tweak to add a checkmark to faded copies of orchestrion rolls seems to have stopped working sometime within the last couple weeks. I've tried disabling/reenabling, and checked in with some friends as well, but it looks like it's not working all around.

Thanks for all your hard work! ♥

**Comment by Callindrill** [comment]
I just opened up my tweaks and was trying to find if this got disabled... and then came here to find this issue.

**Comment by Trupacz** [comment]
I can confirm it is not working on my version as well v1.8.6.1 on Dalamud D7.5.0.2

**Comment by Caraxi** [comment]
Fixed with 203a9211eef4a9d09f7c896eb8eca7d49887c5c7
Will be available in next plugin update
