### ISSUE TITLE
New Player Question

### ISSUE THREAD

**Issue by ChilledTrong** [Caraxi/SimpleTweaksPlugin#564]
sorry i don't think this is an issue im just not sure how else to comment. 

im a new player and looking at mods for the first time. 
is there way to see what this mod does? like screenshots or a list of features? 

new to github so i don't really know how to use it if its already listed somewhere. 
just wondering like with wow add-on's if there's some sort of preview i can look up? 

sorry again for listing this as in issue free to close it immediately

**Comment by Caraxi** [comment]
There is now a [Tweak List](/Caraxi/SimpleTweaksPlugin/blob/main/Tweaks.md)
