### ISSUE TITLE
[bug] Chat Name Colours

### ISSUE THREAD

**Issue by drejjmit** [Caraxi/SimpleTweaksPlugin#576]
``Chat Name Colours`` only partially works.
v1.8.7.2
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/15526476/f4ba75ad-cff5-41e4-8909-6d9af7f9e012)

Edit: Seems to work in Say,Tell, CWLS, LS but not Party

**Comment by Caraxi** [comment]
Will be fixed in next version
0ea51edb8f3dd5c33fb38378b17e0395381a0ef0
