### ISSUE TITLE
[Bug] Tweak: Custom Time Formats issue

### ISSUE THREAD

**Issue by Rueby** [Caraxi/SimpleTweaksPlugin#577]
**Tweak Name : Custom Time Formats**
**Issue : Prevents cycling through different times** 
Prior to 6.4 this was not a problem. Having this tweak active prevents the ability to cycle through ET/LT/ST depending on whatever option you have selected while displaying the correct tooltip. I can only reference to having only one time active since that was what I used prior and I know how it used to work but it's safe to say all three options are affected [?]

For example if LT is selected, only LT time will display in the Server Info Bar, trying to cycle through it to display ST/ET time only changes the tooltip and LT will always be displayed.

Here's some screenshots; they only really show the incorrect tooltip (I don't know how to record gifs sorry).
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/92205577/e7d20d9b-47eb-454c-8255-0c45c3cfdc3d)
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/92205577/2d5c8615-0a30-4e73-83b4-91c153496191)
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/92205577/8cbea3da-7e8b-4aac-8a0e-877234d3ab29)
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/92205577/248e7cbd-d0c8-4a79-a80f-99f61096cdd6)

**Comment by Caraxi** [comment]
Fixed with d7c174217fc561487b044579a679ad8a4f5347e8
will be in the next version
