### ISSUE TITLE
[Feature Request] Automatically turn on auto-text advance in voiced scenes and disable when not voiced

### ISSUE THREAD

**Issue by UserReshi** [Caraxi/SimpleTweaksPlugin#582]
No clue if this is even possible. I haven't looked too much into how everything works under the hood. But I like having auto-text advance enabled in voiced cut-scenes, but then I get caught off guard when the next part of the quest is non-voiced and I get distracted by somebody/something while trying to read and miss part of the quest. If this is something that requires manual keying for every quest, please ignore, that's way too much work! But if there is something visible via Dalamud that indicates when a voiced cutscene starts, that would be nice. Thank you!

**Comment by ryankhart** [comment]
I think this is included in the vanilla game now thanks to Dawntrail, I'm pretty sure, because there's an option for me in the native UI, and unless I have a really clever plugin I installed and forgot about.

This can probably be closed as a "not planned" or something.

**Comment by PicoLegion** [comment]
Yep! It was in the 7.0 patch notes at the bottom of the "Quests" section. [link](https://na.finalfantasyxiv.com/lodestone/topics/detail/d7db61f938f9cea65e4c5cd261918edb036b3004#random-c39d4a9d49690ec34ef44502db3815e54db77c39)

I have been wanting this for so long.
