### ISSUE TITLE
[Suggestion][Adjust Equipment Positions] Cursor movement when enabled

### ISSUE THREAD

**Issue by torakiti2017** [Caraxi/SimpleTweaksPlugin#589]
*Sorry the image is hard to see.
The following is the behavior that seems to be NG.
-Current: Crystal: Left input → Main arm
 Request: Crystal: Left input → INT

-Current: Average item level: Left input → Crystal
 Request: Average item level: Left input → Left ring

The following are actions that would be beautiful if improved.
-Current status: Main arm: Left input → INT
 Request: Main arm: Left input → MND

-Head: Left input → MND
 Request: Head: Left input → Physical defense

-Body: Left input → Physical defense
 Request: Body: Left input → Magic defense

-Currently: Hand: Left input → Magic defense
 Request: Hand: Left input → Attack magic

-Current: Legs: Left input → Attack magic
 Legs: Left → Spell speed

-Current: Legs: Left → Spell Speed
 Request: Legs: Left → Fortitude

[Adjust Equipment Positions] OFF
![ParameterWindow Adjust Equipment Positions-OFF](https://github.com/Caraxi/SimpleTweaksPlugin/assets/86459831/b4f3c528-35c8-42d6-a271-004ce5b77aff)

Current operation with [Adjust Equipment Positions] ON
![Tweeks　パラメータ](https://github.com/Caraxi/SimpleTweaksPlugin/assets/86459831/19748b9a-742f-4aa6-b626-37fe4ca61ea0)

Requested behavior with [Adjust Equipment Positions] ON
![Tweeks　パラメータ のコピー](https://github.com/Caraxi/SimpleTweaksPlugin/assets/86459831/83a136d0-81ce-4ffb-a50a-31db6f222431)

**Comment by Caraxi** [comment]
I've taken your suggested navigation layout and added it. thank you
It will be available in the next update
4f29c442926b6635c87b75bf08cb2afeb67f8671
