### ISSUE TITLE
[Bug?] Smart Nameplates

### ISSUE THREAD

**Issue by surftumbled** [Caraxi/SimpleTweaksPlugin#593]
I'm aware this isn't an additional to the main plug-in specifically by you/Caraxi (or assuming so, since it's showing it's by "UnknownX) - but the UI Tweaks for the "Smart Nameplates" seems to have stopped work after one of the last couple of in-game maintenances. I've attempted to disable and then delete Simple Tweaks, then re-add it, and still come up with the same issue... It's supposed to turn off nameplates for users (specifically) while in combat and, as already stated, this seems to be broken currently. I also had a friend test enabling this setting/tweak, and it also doesn't work for them. So I'm not sure if there's something that could be fix or not, but wished to inquire.

Thanks!

**Comment by Caraxi** [comment]
Should hopefully be fixed in the next update cd11c168046a546a7b8a92814304c621ce3b558b
Please reopen if it still has issues in next version
