### ISSUE TITLE
Turning on examining ilevel crashes the plugin

### ISSUE THREAD

**Issue by Aida-Enna** [Caraxi/SimpleTweaksPlugin#6]
As soon as I turned on the "examine ilevel of other players" option, the plugin crashed and does so now every time I turn it on.

**Comment by Caraxi** [comment]
If you’re using debug dalamud, it is likely Lumina panic.
If you built Simple Tweaks from repo it is likely the font double pop which I forgot to push fix for

**Comment by Aida-Enna** [comment]
Nah, I'm using release dalamud, and I'm using the one it downloads.

**Comment by Aida-Enna** [comment]
Some other people in the plugin_issues_help channel on goat's discord are having the same issue as well.

**Comment by Caraxi** [comment]
Should be resolved now once you update. Something changed in the API between my testing and dalamud being opened to the public... lol

Sorry for inconvenience

**Comment by Aida-Enna** [comment]
No worries, thanks for the speedy update! :smile:
