### ISSUE TITLE
List of tweaks is not actually findable by the layman

### ISSUE THREAD

**Issue by TheGinGear** [Caraxi/SimpleTweaksPlugin#605]
Hi, I just atarted playing ff14, and I was annoyed by the base launcher, so I went ahead and installed [FFXIVQuickLauncher](https://github.com/goatcorp/FFXIVQuickLauncher). I then noticed that plugins were a thing, and when using the plugin browser, found this plugin, and was interested with it by virtue of it being the most used plugin! However, I don;'t know what it actually does, because al it says is this: ![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/39550332/ed18607e-d57d-44b8-8d8b-6f17594d84eb)

There's no github wiki,m and no link to the list in the github readme front page; is it in some folder or something? You can't really expect people with no technical knowledge to know where to look in a githup repo source code for a simple list. For example: me.

Or has the list since been removed and the plugin description innacurate?

**Comment by Caraxi** [comment]
> Or has the list since been removed and the plugin description innacurate?

This is true, There used to be a list but it was removed because it got too giant and unmanageable

**Comment by Caraxi** [comment]
https://github.com/Caraxi/SimpleTweaksPlugin/blob/main/Tweaks.md
