### ISSUE TITLE
"View on Teamcraft" item hotkey is spawning new processes that aren't closed

### ISSUE THREAD

**Issue by CharonM72** [Caraxi/SimpleTweaksPlugin#61]
Hello,

I frequently use Ctrl+T on items to open them in my Teamcraft standalone application (it is super super useful), but, whenever I do, it appears to spawn a set of three new "FFXIV Teamcraft.exe" processes each time I hit the hotkey, that are never closed, even after I close FFXIV. These processes just continue to sit around and eat RAM - see the screenshot below.

Setting it to open in browser would likely fix it, but that is much less convenient for me than using the app. Is there any solution to this (such as ensuring the temporary processes get killed once it opens in Teamcraft)?

I brought this up in the Teamcraft discord as well but they said that it's an issue with the Dalamud plugin, not Teamcraft itself.

Thanks!

![image](https://user-images.githubusercontent.com/1299220/126877930-27eab790-62ba-4a63-8595-93911adb6be7.png)

**Comment by Caraxi** [comment]
If it spawns any teamcraft process, that is teamcraft's problem. I only use the methods teamcraft itself provides to access it.
