### ISSUE TITLE
Icon ID differ in between Tweaks

### ISSUE THREAD

**Issue by Camuroi** [Caraxi/SimpleTweaksPlugin#612]
I tried to use Extended Macro Icons to get some specific icons on my macros.
I used the Tweak "Show ID" without any options enabled and with all options enabled one at a time as well as at the same time.
The shown IDs never matched up with the Icon shown via "Extended Macro Icons".
One example is the icon for the Main Command "Linkshells":
Show ID tells me in the Tooltip its ID is supposed to be 28. 
When used with "Extended Macro Icons" I instead get the icon for the Main Command "Keybind" - which "Show ID" tell me is supposed to be ID 20.
The ID that shows the icon for the Main Command "Linkshells" using "Extended Maco Icons" is 11.

I have not found anyone talking about this so I thought it might be an issue with my mods or plugins at first - but after disabling everything except Simple Tweaks with these two tweaks enabled only the issue persisted.

Hope this can be fixed :)

Thanks for all the amazing work on this plugin!

**Comment by Caraxi** [comment]
Icon IDs and Action IDs are different

**Comment by Camuroi** [comment]
Ah, sorry for the mistake on my part then. Is there any way to find out/show the icon IDs then? And if not: Could this be implemented in Simple Tweaks?
I realize I could scroll through all the Icon IDs in the documentation of xivapi but as far as I can tell this should be possible to implement in a plugin, no?

**Comment by pikajude** [comment]
I had the same question. FWIW, you don't need to scroll through xivapi, you can just use the `IconID` field returned from `https://xivapi.com/item/$id`, that has worked for me
