### ISSUE TITLE
[Bug] "Expended Currency Display" list not displaying properly

### ISSUE THREAD

**Issue by McSpooks** [Caraxi/SimpleTweaksPlugin#614]
Hello,

The Expended currecy display seems to be having some trouble rendering properly on my end.
I don't know if this is useful information, but my screen resolution is 3440x1440, I use the in-game High UI resolution setting.
Moving some currecies up and down the list makes some digits disappear, but no matter the position, it seems that numbers with more than 3 digits don't render properly.
I'm unsure of what information might prove useful to replicate and identify the issue, so by all means, let me know if you need anything else I could provide.

![ezgif-3-ec56f6be0a](https://github.com/Caraxi/SimpleTweaksPlugin/assets/15790377/eb44a68b-7c6b-42f5-87ba-e118ee798bc8)

**Comment by Valgrifer** [comment]
same problem, but a little different, with the game in French, when a number has more than 3 digits, this number no longer displays nothing after the space and and an apparent artifact, flashes everywhere on the screen.
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/13664715/d22a2149-011d-4ee3-b05a-6d768b00c118)
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/13664715/08b441fb-d369-43a6-bf93-4691ed509001)

**Comment by Caraxi** [comment]
094ca43ef5ec6a0263b2e46a4278d6151f326659
should be fixed in next version, whenever that is
