### ISSUE TITLE
[Feature Request] A Command to Leave Dungeons

### ISSUE THREAD

**Issue by Rellawing** [Caraxi/SimpleTweaksPlugin#615]
[Feature Request] A Command to Leave Dungeons

As all know, at the moment we have to open the duty finder and click leave (a two click process) to get out of a dungeon/raid etc. It'd be helpful if a command such as /leaveduty was added.

Thanks! :3

**Comment by Caraxi** [comment]
Added with a7d29d613c5d3c6e867cbc631458a7899617e216
