### ISSUE TITLE
[Feature Request] Automatic Party Replacement Recruitment When Users Leave a Duty

### ISSUE THREAD

**Issue by Rellawing** [Caraxi/SimpleTweaksPlugin#616]
[Feature Request] Automatic Party Replacement Recruitment When Users Leave a Duty

It'd be useful that if you happen to be the leader and had this potential tweak enabled, it would immediately recruit replacements for those sticky moments where someone decided to bail from the duty.

I dunno how possible this would be to implement, but it seems like it'd be useful.

**Comment by Caraxi** [comment]
no automation

**Comment by Rellawing** [comment]
How about opening the duty list when someone drops when you're the leader
instead? No auto recruitment, but making sure that the leader knows that
it's their duty to replenish or disband.
