### ISSUE TITLE
Unable to move the cursor when [Adjust Equipment Positions] is enabled.

### ISSUE THREAD

**Issue by torakiti2017** [Caraxi/SimpleTweaksPlugin#634]
Thank you for responding to our previous suggestions.
https://github.com/Caraxi/SimpleTweaksPlugin/issues/589

After the 6.5 update, it is no longer possible to move left from the soul crystal/armour.
-Profile
-Class/Job
-Reputation
<img width="433" alt="1" src="https://github.com/Caraxi/SimpleTweaksPlugin/assets/86459831/dabff33d-2a0c-44c1-bdb7-08a5e695a216">
<img width="430" alt="2" src="https://github.com/Caraxi/SimpleTweaksPlugin/assets/86459831/1bf41544-8349-4255-8a14-2a2157c0be6c">
<img width="432" alt="3" src="https://github.com/Caraxi/SimpleTweaksPlugin/assets/86459831/ba96ac36-1374-44d5-9baf-0468b3928853">
Thank you for your confirmation.

**Comment by Caraxi** [comment]
a3e9fbdc550d06924296af280d36332e7e2f683f
Will be available in Simple Tweaks `1.9.1.0`
