### ISSUE TITLE
[Feature Request] An action to update gear set

### ISSUE THREAD

**Issue by mnky9** [Caraxi/SimpleTweaksPlugin#635]
I love the action to equip recommended. I would love to string on to that update gear set so that I don't have to open the character screen at all.

**Comment by mnky9** [comment]
> you can do this with [_/gearset save_](https://na.finalfantasyxiv.com/lodestone/playguide/db/text_command/9fcb6012adb/)

Thanks, I didn't know that one existed. However, it doesn't solve my problem. Is there a way to save it to the current set? Otherwise i would need a macro for each job.

**Comment by Caraxi** [comment]
> > you can do this with [_/gearset save_](https://na.finalfantasyxiv.com/lodestone/playguide/db/text_command/9fcb6012adb/)
> 
> Thanks, I didn't know that one existed. However, it doesn't solve my problem. Is there a way to save it to the current set? Otherwise i would need a macro for each job.

You can just do `/gearset save` with nothing else and it'll save the current gearset

**Comment by Caraxi** [comment]
> I tested this before I made my comment, but the documentation doesn't say that he gearset number is optional. If used without one it applies to the current active gearset, you should try it

It is optional, but it just makes a new gearset if not provided

**Comment by Caraxi** [comment]
A new command tweak will be available for this in the next update
