### ISSUE TITLE
[Feature request] Set quantity to 1 when using "Retrieve Quantity"

### ISSUE THREAD

**Issue by zoyavel** [Caraxi/SimpleTweaksPlugin#653]
Hello! I think it would be great to have the option to set the quantity to 1 when using the action "Retrieve Quantity" from retainers and saddlebags, just like when splitting item stacks. I usually need to retrieve just 1 item when crafting or getting dyes and it is not practical when the game always sets the quantity as the maximum by default.
Thanks in advance!

**Comment by Caraxi** [comment]
Will be in the next update
