### ISSUE TITLE
[BUG] Sync gatherer hotbars not working

### ISSUE THREAD

**Issue by kobaultgp** [Caraxi/SimpleTweaksPlugin#655]
My gatherer BTN and MIN hotbars dont sync with eachother, but the crafter ones do.

**Comment by Caraxi** [comment]
Did you enable some bars for it to sync?

**Comment by kobaultgp** [comment]
yes , ive tried the same hotbar numbers as the crafters, ive tried different hotbar numbers, ive tried disabling and reneabling tweaks, ive tried disabling and renabling the sync option.

**Comment by kobaultgp** [comment]
I recently found something most weird where syncing crosshotbar 6-7 for gatherers work (whatever crosshotbars arent being synced by crafters), but then thatll sync for every job/class not just min and btn...
