### ISSUE TITLE
Was Improved Crafting Log removed?

### ISSUE THREAD

**Issue by Revonlieke** [Caraxi/SimpleTweaksPlugin#658]
Was Improved Crafting Log removed?

Modifies the Synthesize button in the Crafting Log to switch job or stand up from the crafting position, allowing you to stop crafting without closing the crafting log.

Or is it in queue for an update?

**Comment by GoblinGuide** [comment]
I see it, but when I try to activate it I get this:
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/12886590/49b60bfd-63d0-451a-aecb-d630397d93fb)

So I guess I technically have a different question, but also, it's really the same question.

**Comment by Caraxi** [comment]
> I see it, but when I try to activate it I get this: ![image](https://user-images.githubusercontent.com/12886590/282274379-49b60bfd-63d0-451a-aecb-d630397d93fb.png)
> 
> So I guess I technically have a different question, but also, it's really the same question.

I'm not sure what that is, I suspect interference from another plugin working with crafting log too

**Comment by Revonlieke** [comment]
Thanks for fixing it. Works for me.
