### ISSUE TITLE
Sync Crafter Bar Not Syncing Bar 4

### ISSUE THREAD

**Issue by MorsetTheDeer** [Caraxi/SimpleTweaksPlugin#662]
I recently started encountering an issue with the Sync Crafter Bars Tweak. Hotbar 1, 2, and 3 all sync perfectly fine, and so do Hotbars 5, 6, 7, 8, 9, and 10. But for some reason, Hotbar 4 in particular won't sync between classes, despite being selected in the Settings for this Tweak. In fact, this specific Hotbar appears to be immune to change in general, remaining the same regardless of what class is being switched to, even though all the others change as expected.

**Comment by MorsetTheDeer** [comment]
My mistake, I tested a little more, and noticed that it's Hotbars past 3, so, 4 through 10, that have trouble syncing. I just tried using a layout where I replaced Hotbar 4 with 7, and I had the same issue with it not syncing between Crafting classes.

**Comment by kobaultgp** [comment]
im having a similar issue, except for me its gathering hotbars. I have crosshotbars 2-4 syncing for crafters, but selecting the same ones for gatherers dont work. I recently found something most weird where syncing crosshotbar 6-7 for gatherers work, but then thatll sync for every job/class not just min and btn...

**Comment by Caraxi** [comment]
Please make sure you're not trying to sync a shared hotbar with these tweaks
