### ISSUE TITLE
[Feature Request] Add option to only show rested as percent in UIAdjustments@ExpPercentage

### ISSUE THREAD

**Issue by bidaumm** [Caraxi/SimpleTweaksPlugin#670]
As title.. current options are as follows
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/30007328/07927392-e6c8-4836-a641-1fe25184a15f)

Suggestion is to add a sub-option to "Show Rested Experience" to work as such

- Only show percentage
- Show Rested Experience
    - Show only Rested Experience as percentage

To allow options to display such as.. 
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/30007328/851b4b80-ae6b-425a-83ce-6738c3375778)

**Comment by Caraxi** [comment]
Will be available in next update
