### ISSUE TITLE
[Feature Request] Tooltip appendix when Gear can go in the Armoire

### ISSUE THREAD

**Issue by TimeBender25** [Caraxi/SimpleTweaksPlugin#675]
Nothing major, but it would be nice to be able to tell at a glance whether or not something can go in the Armoire in lieu of the Glamour Dresser. Something akin to the Geatsets Label is what I'm imagining.

Kinda surprised that a plugin like this isn't already a thing, but it being an config option here instead of a full, complete, and separate thing makes the most sense anyways.

**Comment by TimeBender25** [comment]
Also how do I label this as Suggestion, it didn't let me when i made it

**Comment by Caraxi** [comment]
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/11886749/03465047-cbe4-4526-bfe0-2e89888f5a60)
it exists already in vanilla

**Comment by TimeBender25** [comment]
Ah, I am a fool then

Thank you
