### ISSUE TITLE
[Feature Request] gear equippable from hot bars

### ISSUE THREAD

**Issue by Tyrannical-Potato** [Caraxi/SimpleTweaksPlugin#695]
You can currently hotbar gear pieces, but you cant do anything with them! I think being able to equip/unequip gear pieces from the hotbar would be neat.

PS: Thanks for the excellent plugin, cant function without it now!

**Comment by Ferikisekai** [comment]
I'd also like to request a command to equip gear by ID or name. Something like /equip [ID/name].

**Comment by Caraxi** [comment]
0bf3b47c6f9bfed6cbb54139d911945364dcd4df
This should be in the next update
