### ISSUE TITLE
Wrong desynth skill number shown

### ISSUE THREAD

**Issue by minrathous** [Caraxi/SimpleTweaksPlugin#7]
When using the Show Desynth Skill feature, certain skill numbers will be shown as 0 when they aren't, or shown as 573 (higher than the cap?). There are 1 or 2 classes that show as the correct number, but the majority are having these issues.
![desyntherror](https://user-images.githubusercontent.com/24889007/101795167-9e1bd000-3ad5-11eb-8c59-8e08b155db65.png)

**Comment by Caraxi** [comment]
Fixed already in 46ca528
Please update the plugin in the installer
