### ISSUE TITLE
[Bug Report] Hide Job Gauge

### ISSUE THREAD

**Issue by Lanselotto** [Caraxi/SimpleTweaksPlugin#70]
After enabling and then disabling Hide Job Gauge, if I change job, the old Job Gauge remains with the new one.
![image](https://user-images.githubusercontent.com/39704475/130067054-05ada6f0-5e55-419b-826b-aa7e13e1574b.png)

**Comment by Caraxi** [comment]
Should be fixed, I think. Please reopen if it still happens
