### ISSUE TITLE
Extended Macro Icons

### ISSUE THREAD

**Issue by V3semir** [Caraxi/SimpleTweaksPlugin#704]
How does it exactly work? I tried putting IDs from Icon Browser and https://xivapi.com/docs/Icons, and it doesn't work. 

I tried inside macro:
/macroicon 104
/macroicon #104
/macroicon # 104
/micon 104
/micon #104
/micon # 104

**Comment by Caraxi** [comment]
it says how in the description
```
/micon 104 id
```

**Comment by V3semir** [comment]
> it says how in the description
> 
> ```
> /micon 104 id
> ```

Oh, I thought the "id" part is a placeholder for actual ID, and got confused. I'll test it in a bit. Thanks!
