### ISSUE TITLE
[Feature Request] Commands to Use Fashion Accessories and Collection

### ISSUE THREAD

**Issue by Rellawing** [Caraxi/SimpleTweaksPlugin#708]
[Feature Request] Commands to Use Fashion Accessories and Collection

It would be nice to be able to macro the Aether Compass in time for Dawntrail, when we'll be attuning to 6 new area's aether currents. I think it would be useful to be able to toggle on and off Fashion Accessories as well by command.

**Comment by Caraxi** [comment]
Game already has a command for fashion accessories

https://na.finalfantasyxiv.com/lodestone/playguide/db/text_command/803679db189/

Collection items like aether compass can be dragged into hotbar, I'm not sure why you would need to macro something like that personally

**Comment by Caraxi** [comment]
A command has been added for collection items thanks to nebel
will be in the next plugin update
