### ISSUE TITLE
Ability to open plugin inside gpose

### ISSUE THREAD

**Issue by Westlaketea** [Caraxi/SimpleTweaksPlugin#715]
I encountered a problem that the screenshot is not rendered due to the large number of actors, so needed to change the latency in "screenshot size" tweak, but the plugin does not open inside gpose.

**Comment by Caraxi** [comment]
It only hides in GPose because you enabled the setting in Dalamud to hide plugin windows in gpose

`/xlsettings` -> `Look & Feel` -> `Hide plugin UI while gpose is active`
