### ISSUE TITLE
[Feature Request] Add Parameter Bar Adjustments to setopt

### ISSUE THREAD

**Issue by bladehawkz** [Caraxi/SimpleTweaksPlugin#74]
Many classes do not use mana, but some do. This means that easily setting mana bar off to those that don't, and on for those that do is obviously useful.

Adding it to setopt (and letting players put the option into a standard gear change macro) would be highly helpful.

**Comment by jdarr08** [comment]
Yes, please! This would be fantastic!

**Comment by bladehawkz** [comment]
Saw new features in incoming build. Closed.
