### ISSUE TITLE
Parameter Bar Adjustments - MP bar not hidden on VPR

### ISSUE THREAD

**Issue by Sparrows413** [Caraxi/SimpleTweaksPlugin#751]
Viper doesn't use MP for any of its abilities, but the MP bar remains visible when "Hide MP bar on jobs that don't use MP" is checked. not game-breaking in any way, just thought I'd let you know.

Thank you for the update!

**Comment by Caraxi** [comment]
3d5a7cad54a6a49f70c41d5779eef3ea7f85a375
