### ISSUE TITLE
Quick Auto Sell Tweak Removed?

### ISSUE THREAD

**Issue by KariousNuance** [Caraxi/SimpleTweaksPlugin#752]
Quick Auto Sell was a tweak available in this plugin prior to Dawntrail's release, and was my most used feature. Upon updating to the current release, this tweak is no longer available. Will it be available again? Is it incompatible with the newest game update?

**Comment by Sparrows413** [comment]
Did you try reading the popup?

**Comment by KariousNuance** [comment]
The only popup I received was to submit anonymous data after it updated. ???

**Comment by bluerhino96** [comment]
![bruh](https://github.com/Caraxi/SimpleTweaksPlugin/assets/70051449/983ba24e-2beb-45d3-9d3c-0c204a90e877)

**Comment by KariousNuance** [comment]
Weird, that never showed for me. Okay.
