### ISSUE TITLE
Target Castbar text feature removed?

### ISSUE THREAD

**Issue by vaxd627** [Caraxi/SimpleTweaksPlugin#753]
Has the target Castbar text separation feature been removed intentionally? The feature was there and a godsend to me before Dawntrail, may I ask it be reimplemented?
The image attached is what the tweak used to do. Simply moved the text above the bar.
![cast bar2](https://github.com/Caraxi/SimpleTweaksPlugin/assets/175063866/2208e916-03c5-4f8c-9dc7-7ab1a42543fb)

**Comment by vaxd627** [comment]
why did you close the thread? this isn't a new feature its something that was implemented before dawntrail, can you at least give me a reason why it was removed?

**Comment by Caraxi** [comment]
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/11886749/19e92ff7-feab-46d1-a128-94b6dc9d62ba)
because you skipped the message asking you specifically not to post github issues about missing tweaks

**Comment by vaxd627** [comment]
alright my bad then, i never saw that window pop up. maybe cause all my plugins updated at once.
