### ISSUE TITLE
[Feature Request] normal running in SW and SE directions in Legacy mode

### ISSUE THREAD

**Issue by msoltyspl** [Caraxi/SimpleTweaksPlugin#76]
(not sure if this kind of tweak falls into 'simple' category)

Anyway - with camera set to legacy mode, we can move character at full run speed in N, W, S, E, NE and NW directions. But SW and SE are still limited to slow-walking backwards. Would be great if it was easily fixable.

**Comment by Aireil** [comment]
Don't strafe and use the tweak to lock the camera.

**Comment by msoltyspl** [comment]
Hmm, how is strafing (if you mean E and W) relevant to this ?

**Comment by Aireil** [comment]
Slow walking does not exist in legacy unless you strafe. Try it.

**Comment by msoltyspl** [comment]
There is no slow walking in cardinal or forward diagonal directions. Only diagonal S+W and S+E. I know I can just workaround it with mouse and by not mixing S+W or S+E . But perhaps it's easily fixable - thus my feat request.

**Comment by Aireil** [comment]
Why don't you try to replace your strafing keybinds by turning and try again instead of not reading what I write.
> Slow walking **does not exist in legacy unless you strafe**.

That includes any combinations of directions.

> Try it.

**Comment by msoltyspl** [comment]
Never in my lifetime I expected 'turn left/turn right' to strafe me left/right correctly, what the actual fuck.

So yea, after you wrote "**replace**" I went back to keybinds and checked those. I knew those existed, but had them unbound prooly when I first started the game years ago (considering it likely rotated my char in standard mode back then). You could have been slightly clearer about that shit in keybinds though, lol.

Anyway, I'll take that as a simple fix =) You solved years of my suffering.
