### ISSUE TITLE
Screenshot Improvement

### ISSUE THREAD

**Issue by Eph4723** [Caraxi/SimpleTweaksPlugin#760]
You may have addressed this elsewhere and i did not see it or overlooked it. Is this feature gone or just needs to be updated?
I have experimental mode on but i do not see this tweak on the list anymore.

**Comment by Caraxi** [comment]
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/11886749/8c2acfd7-637d-4634-9e31-9bdda23fc2db)
the message you ignored asked you not to post about missing tweaks

**Comment by Eph4723** [comment]
my apologies.
