### ISSUE TITLE
[Feature Request] A Command to Toggle Between Gamepad and Mouse Modes

### ISSUE THREAD

**Issue by Rellawing** [Caraxi/SimpleTweaksPlugin#775]
[Feature Request] A Command to Toggle Between Gamepad and Mouse Modes

As I've started dabbling with playing with a gamepad, since I'm fortunate enough to own a handheld PC (and it plays FFXIV quite nicely), I thought it'd be wise if I try to learn how to play as many jobs as possible on a gamepad.

For the sake of practice, I train playing with a gamepad on my main rig. But given that I'm alternating using a gamepad and mmo mouse + a gaming keypad, it's a bit annoying to have to open the Character Settings and click the button whenever I want to switch the mode. Being able to macro this would be way easier!

Thanks for your consideration and hard work!

**Comment by Caraxi** [comment]
when Set Option command comes back this can be done with `/setopt GamepadMode toggle`

that tweak isn't available currently but will return soon
