### ISSUE TITLE
[Feature Request] Automatically Enable Collector's Glove when switching to Fisher

### ISSUE THREAD

**Issue by drintath** [Caraxi/SimpleTweaksPlugin#780]
The number of times I've caught a collectable fish only to realize I forgot to click this button so it is worthless is TOO HIGH, I have no idea why this even exists and collectable fish are not just always marked as collectables when you catch them or at the very least why this is not enabled by default like Sneak but I digress. It would be lovely if SimpleTweaks would remember to use Collect every time I switch to Fisher automatically.

**Comment by Caraxi** [comment]
no automating something that sends things to server, sorry.
