### ISSUE TITLE
[Bug] Sticky chat sending to wrong chat channel

### ISSUE THREAD

**Issue by drejjmit** [Caraxi/SimpleTweaksPlugin#806]
Sticky chat swaps to CWL2 in this example, but still sends chat to /say (or previous chat channel)

![image](https://github.com/user-attachments/assets/ebd4f9f4-2181-4a98-9fc4-61f17b48be61)

I think it's a @MidoriKami tweak.

**Comment by SayuShira** [comment]
Having the same issue. Can get somewhat awkward.
Its not sticky, i guess, only the channel name shown is. I am in party chat, i "/fc msg" "another msg" and another msg showed FC as the chat but was then send off into party chat

**Comment by drejjmit** [comment]
Fixed with https://github.com/Caraxi/SimpleTweaksPlugin/pull/812
