### ISSUE TITLE
[Bug] Always Yes Tweak: Not affecting Desynthesizing items

### ISSUE THREAD

**Issue by PrincessTsukina** [Caraxi/SimpleTweaksPlugin#809]
With the "Always Yes" tweak enabled, desynthesizing items defaults the cursor to "cancel", even with the "Default cursor to checkbox when one exists" and "Desynthesis" options enabled.

Functions correctly on every other option I've tested except Desynthesizing items specifically.

**Comment by grilovan** [comment]
huh weird. like one hour ago I desynthesized like a lot of gear and it always selected cancel when exiting out. cursor would show up and with another click it did it.

**Comment by Aireil** [comment]
Should be fixed in the next SimpleTweaks update with #810, not exactly sure what changed, but 🤷‍♂️.
