### ISSUE TITLE
Tweak Request: Auto refresh Raw Materials List

### ISSUE THREAD

**Issue by Loseriana** [Caraxi/SimpleTweaksPlugin#839]
The Raw Materials List tab needs you to constantly click the button to update what its in your inventory. My request is an auto update tweak, that updates the list after I've ended my gathering on that node.

![Screenshot 2024-08-10 194118](https://github.com/user-attachments/assets/f09a0bde-d92e-46ea-a775-209515ead331)

Sorry if something like that already exists.

**Comment by Caraxi** [comment]
Should be easy but I'll need to check if it does network requests for some reason

**Comment by Caraxi** [comment]
Will be available in a future update
