### ISSUE TITLE
Try On Correct Item makes un-glamoured items unable to be previewed

### ISSUE THREAD

**Issue by ArvidGreymorn** [Caraxi/SimpleTweaksPlugin#857]
Hi!  This seems to be an issue for me starting with today's update (v1.10.0.6).  Whenever I try to try on a piece of gear that is un-glamoured (specifically directly from my inventory, tested with a number of gear pieces including Heirloom Gaskins of Aiming, Last Earrings of Slaying, and Angel Brush), the try on window will open, but there will be no items selected for preview.  It simply shows my character in his smallclothes with every equipment slot empty.  Items that are glamoured DO appear to work correctly, just not items that do not have a glamour applied.

**Comment by kayl-salad** [comment]
I've been trying to try on any gear and _none_ of it is showing up at all, and disabling Simple Tweaks was my first go-to, and it fixed the issue. So I'm not sure which Tweak is causing my issue but I think it's probably related to your own? I can submit a separate issue if need be but I figured doing so might be redundant

**Comment by Caraxi** [comment]
its fixed in next version

**Comment by kayl-salad** [comment]
Awesome, I noticed! Thanks so much.
