### ISSUE TITLE
[Feature Request] Border options for Large Cooldown Counter text

### ISSUE THREAD

**Issue by JoshFrey** [Caraxi/SimpleTweaksPlugin#86]
On some of the icons, it's pretty difficult for me to see the cooldown text. It would be nice to have some border options for the text. I tried to give this a go myself, but was struggling to get the repo building locally... if you happen to have a dev guide up there, I'd love to take a look!

**Comment by drejjmit** [comment]
I would love a Font color as well. I want yellow instead of white. Maybe that would help you as well.

**Comment by Caraxi** [comment]
Added an option to change colour and add an outline with 55c773cfd8015c7c32acc4873ada420609160513 available in current version of simple tweaks.
