### ISSUE TITLE
rename chat tabs causes all tabs to collapse on themselves

### ISSUE THREAD

**Issue by ListeningGarden** [Caraxi/SimpleTweaksPlugin#866]
as of the newest update, simple tweaks has an issue where all of the chat tabs collapse into each other, making it impossible to switch between them
![ffxiv_dx11_kXP2JNXavJ](https://github.com/user-attachments/assets/03b57fbb-f21c-478c-bec2-a235f40dc7cd)

when attempting to disable the "rename chat tabs" section, it produces the following error in the log

![image](https://github.com/user-attachments/assets/a0521d4f-2671-4016-bb08-c3d3a557b403)

**Comment by Caraxi** [comment]
Fixed in latest version
