### ISSUE TITLE
"Hide chat" tweak is disabled after restarting the game

### ISSUE THREAD

**Issue by bayta-88** [Caraxi/SimpleTweaksPlugin#868]
Hello. This is one of my favorite plugins so thanks a lot for all your work in building it and adapting all the tweaks for Dawntrail :-).

When "Hide chat" was re-introduced a few days ago I enabled it but after restarting the game, it goes back to being disabled every time. Currently I have to enable the tweak manually each time I login even though the JSON configuration file lists "ChatTweaks@HideChat" among the enabled tweaks before I login. This doesn't seem to happen with any of the others tweaks as far as I know (I enabled multiple of the re-introduced tweaks that night and this is the only one that "disables itself" when I log off).

I attach the configuration file in case it can be useful for debugging:
[SimpleTweaksPlugin.json](https://github.com/user-attachments/files/16971101/SimpleTweaksPlugin.json)

**Comment by Caraxi** [comment]
Thank you

It will be fixed in next update
89c521b545efeea6d3a99cc33072e1fd964d71ac
