### ISSUE TITLE
[Request] "Select next loot window item" tweak causes you to roll at the end of the timer

### ISSUE THREAD

**Issue by Cypher-D1** [Caraxi/SimpleTweaksPlugin#877]
This tweak currently makes you automatically roll need if you can, or greed otherwise when the timer runs out. Regardless of what you want to roll. When just going off the name, all I can see it's meant for is to not have to click the next item when selecting need, greed or pass. 
In lower level dungeons I just don't care to open the loot window. 

Could this be added as an option? If nothing selected, then pass?

**Comment by Caraxi** [comment]
I’m fairly sure that’s a vanilla feature, it auto rolls at the end of the timer at a level below greed if nobody else rolled on it. The tweak makes no change to this

**Comment by Cypher-D1** [comment]
> I’m fairly sure that’s a vanilla feature, it auto rolls at the end of the timer at a level below greed if nobody else rolled on it. The tweak makes no change to this

I tried it with and without the tweak. Without the tweak it passed, when it was on loot acted as if I had rolled. I can provide screenshots of my log showing this
