### ISSUE TITLE
Disable Random Chat Name Colour

### ISSUE THREAD

**Issue by gucciBane** [Caraxi/SimpleTweaksPlugin#88]
Would love an option to disable the random part of the new Chat Name Colour options. It would be great for being able to keep track of only a few people. Also, being able to add my own name (currently can, but it doesn't seem to do anything).

Really appreciate this feature, thank you!

**Comment by Noshei** [comment]
Seconding on the being able to color your own name!!

**Comment by Caraxi** [comment]
Done
