### ISSUE TITLE
Preview Unlockable Items - delayed preview in currency exchange

### ISSUE THREAD

**Issue by Sidiousious** [Caraxi/SimpleTweaksPlugin#883]
Steps to repro:
- Enable "Preview Unlockable Items" tweak
- Go to a vendor with previewable items for sale, e.g. Pavli at Dock Poga
- Hover over the items in order

Expected behavior:
item shows correct preview

Actual behavior:
item shows preview for the previous hovered item

1. ![image](https://github.com/user-attachments/assets/9ec881c1-236d-4310-bf00-458b7110383b)
2. ![image](https://github.com/user-attachments/assets/1446ec1f-d2e5-41af-b059-09d3fd772e21)
3. ![image](https://github.com/user-attachments/assets/d01a62e3-9886-474b-a024-81c1204b615f)
4. ![image](https://github.com/user-attachments/assets/754febbf-c93f-4a1e-bae9-41e53fb941a7)

**Comment by Caraxi** [comment]
Incorrect preview fixed with 32da76f6c0f1e79f884dc0ba4b0d8acc9a428ca1
Preview showing in incorrect position 62139dd387586ef14800b2fa6b8ea0883e43accb
