### ISSUE TITLE
[Feature Request] Move coordinates above the minimap

### ISSUE THREAD

**Issue by Dekartea** [Caraxi/SimpleTweaksPlugin#89]
Any possibility of this being added? Would help to make my UI setup just that little bit cleaner, and it's something I've wanted in the game since forever. I'm loving the current minimap tweaks, and I'm super tempted to just hide the coordinates for the UI's sake, but I don't want to lose the functionality of having my coordinates visible at all times.

Cheers

**Comment by Caraxi** [comment]
Done :)

**Comment by Dekartea** [comment]
Hello! I know this is already closed, but I just had the thought that it'd be cool if we also had the option to align the coordinates left/right/centre as well, similar to the Cast Bar Adjustments. Thanks for all your hard work, so keen for this feature!
