### ISSUE TITLE
Possible to disable auto-adjusting camera on Legacy Controls?

### ISSUE THREAD

**Issue by Maxunit** [Caraxi/SimpleTweaksPlugin#9]
(Please label properly ^^")

Hello Caraxi,

I had a request a while ago on the Discord Server, if it is possible to disable the auto-adjusting camera when playing with Legacy Type Controls using a Gamepad and sadly it got no real answer.

Someone told to post it here (under issues and then labeled correctly) and ask you, if that is possible with the Dalamud API and if you would be interested in adding such a feature to your Simple Tweaks Plugin.

I would be very grateful for a reply :)

Cheers,
Maxunit

**Comment by Caraxi** [comment]
I'll add it to the list of things to get to one day if I can. Might not be for a while though

**Comment by Maxunit** [comment]
Thank you, Caraxi :)

**Comment by Caraxi** [comment]
Done in latest version :)
