### ISSUE TITLE
[Bug Report] Shield gauge clips over MP bar when too large

### ISSUE THREAD

**Issue by BSoD38** [Caraxi/SimpleTweaksPlugin#93]
This is rather specific, but when you have a huge shield (for example when a player that has a level many orders of magnitude higher than yours casts a shield spell), the yellow shield gauge will clip over the MP gauge.

![bug](https://i.imgur.com/1OHBHIF.png)

Ways to fix this would be either to clip the rest of the shield gauge and add a marker for each extra gauge (like how it is shown on the party list, or like in KH2 onwards), or simply repeat the shield gauge X times with a different color, in KH1 style.

**Comment by Caraxi** [comment]
Thank you for the report
For now I've just capped it at 100% as a fix, can think about adding an icon for it at a later stage.
